/*
 MinPubSub
 a micro publish/subscribe messaging framework
 @see https://github.com/daniellmb/MinPubSub 
 @author Daniel Lamb <daniellmb.com>

 Released under the MIT License
 MelonJS Game Engine
 Copyright (C) 2011 - 2013, Olivier BIOT
 http://www.melonjs.org

 melonJS is licensed under the MIT License.
 http://www.opensource.org/licenses/mit-license.php

 Tween JS
 https://github.com/sole/Tween.js
*/
var me=me||{};
(function(e){function a(){if(!f){if(!b.body)return setTimeout(a,13);b.removeEventListener?b.removeEventListener("DOMContentLoaded",a,!1):e.removeEventListener("load",a,!1);f=!0;for(var d=0;d<g.length;d++)g[d].call(e,[]);g.length=0}}var b=e.document;me={mod:"melonJS",version:"0.9.7",nocache:"",audio:null,video:null,timer:null,input:null,state:null,game:null,entityPool:null,levelDirector:null,TMXParser:null,loadingScreen:null,TMXTileMap:null};me.sys={ua:navigator.userAgent,sound:!1,localStorage:"object"==typeof e.localStorage,
gyro:void 0!==e.DeviceMotionEvent,nativeBase64:"function"==typeof e.atob,touch:!1,isMobile:!1,fps:60,interpolation:!1,scale:null,gravity:void 0,useNativeAnimFrame:!1,cacheImage:!1,dirtyRegion:!1,stopOnAudioError:!0,pauseOnBlur:!0,preRender:!1,checkVersion:function(a,b){b=b||me.version;for(var d=a.split("."),c=b.split("."),f=Math.min(d.length,c.length),g=0,e=0;e<f&&!(g=+d[e]-+c[e]);e++);return g?g:d.length-c.length}};var c=!1,d=!1,f=!1,g=[];e.onReady=function(c){d||(d=!0,"complete"===b.readyState?
a():(b.addEventListener&&b.addEventListener("DOMContentLoaded",a,!1),e.addEventListener("load",a,!1)));f?c.call(e,[]):g.push(function(){return c.call(e,[])});return this};e.onReady(function(){c||(me.utils.setNocache(b.location.href.match(/\?nocache/)||!1),me.audio.detectCapabilities(),me.sys.touch="createTouch"in b||"ontouchstart"in e||navigator.isCocoonJS,me.sys.isMobile=me.sys.ua.match(/Android|iPhone|iPad|iPod|BlackBerry|Windows Phone/i),me.timer.init(),me.mapReader=new me.TMXMapReader,me.loadingScreen=
new me.DefaultLoadingScreen,me.state.init(),me.entityPool.init(),me.levelDirector.reset(),c=!0)});var k=!1,h=/xyz/.test(function(){})?/\bparent\b/:/.*/;Object.extend=function(a){function b(){!k&&this.init&&this.init.apply(this,arguments)}var d=this.prototype;k=!0;var c=new this;k=!1;for(var f in a)c[f]="function"==typeof a[f]&&"function"==typeof d[f]&&h.test(a[f])?function(a,b){return function(){var c=this.parent;this.parent=d[a];var f=b.apply(this,arguments);this.parent=c;return f}}(f,a[f]):a[f];
b.prototype=c;b.constructor=b;b.extend=Object.extend;return b};"function"!==typeof Object.create&&(Object.create=function(a){function b(){}b.prototype=a;return new b});if(!Function.prototype.bind){var l=function(){};Function.prototype.bind=function(a){var b=this;if("function"!=typeof b)throw new TypeError("Function.prototype.bind called on incompatible "+b);var d=Array.prototype.slice.call(arguments,1),c=function(){if(this instanceof c){var f=b.apply(this,d.concat(Array.prototype.slice.call(arguments)));
return Object(f)===f?f:this}return b.apply(a,d.concat(Array.prototype.slice.call(arguments)))};b.prototype&&(l.prototype=b.prototype,c.prototype=new l,l.prototype=null);return c}}"undefined"===typeof Date.now&&(Date.now=function(){return(new Date).getTime()});"undefined"===typeof console&&(console={log:function(){},info:function(){},error:function(){alert(Array.prototype.slice.call(arguments).join(", "))}});Function.prototype.defer=function(){var a=this,b=Array.prototype.slice.call(arguments);return window.setTimeout(function(){return a.apply(a,
b)},0.01)};Object.defineProperty||(Object.defineProperty=function(a,b,d){if(a.__defineGetter__)d.get&&a.__defineGetter__(b,d.get),d.set&&a.__defineSetter__(b,d.set);else throw"melonJS: Object.defineProperty not supported";});String.prototype.trim||(String.prototype.trim=function(){return this.replace(/^\s+/,"").replace(/\s+$/,"")});String.prototype.isNumeric=function(){return null!=this&&!isNaN(this)&&""!=this.trim()};String.prototype.isBoolean=function(){return null!=this&&("true"==this.trim()||
"false"==this.trim())};String.prototype.contains=function(a){return-1<this.indexOf(a)};String.prototype.toHex=function(){for(var a="",b=0;b<this.length;)a+=this.charCodeAt(b++).toString(16);return a};Number.prototype.clamp=function(a,b){return this<a?a:this>b?b:+this};Number.prototype.random=function(a,b){return~~(Math.random()*(b-a+1))+a};Number.prototype.round=function(){var a=2>arguments.length?this:arguments[0],b=Math.pow(10,arguments[1]||arguments[0]||0);return Math.round(a*b)/b};Number.prototype.toHex=
function(){return"0123456789ABCDEF".charAt(this-this%16>>4)+"0123456789ABCDEF".charAt(this%16)};Number.prototype.sign=function(){return 0>this?-1:0<this?1:0};Number.prototype.degToRad=function(a){return(a||this)/180*Math.PI};Number.prototype.radToDeg=function(a){return(a||this)*(180/Math.PI)};Array.prototype.remove=function(a){a=Array.prototype.indexOf.call(this,a);-1!==a&&Array.prototype.splice.call(this,a,1);return this};Array.prototype.forEach||(Array.prototype.forEach=function(a,b){for(var d=
0,c=this.length;c--;d++)a.call(b||this,this[d],d,this)});Object.defineProperty(me,"initialized",{get:function(){return c}});var m=function(){var a={},b=[],d,c=[],f=0;a.isDirty=!1;a.reset=function(){b.length=0;c.length=0;d=me.game.viewport.getRect();a.makeAllDirty()};a.makeDirty=function(d,f,g){f&&(a.isDirty=!0,me.sys.dirtyRegion&&(g?b.push(g.union(d)):d.getRect&&b.push(d.getRect())));d.inViewport&&c.unshift(d)};a.makeAllDirty=function(){b.length=0;b.push(d);a.isDirty=!0};a.remove=function(b){var d=
c.indexOf(b);-1!=d&&(c.splice(d,1),b.inViewport=!1,a.makeDirty(b,!0))};a.getDrawCount=function(){return f};a.draw=function(a){var d=me.game.viewport.pos.x+~~me.game.viewport.offset.x,g=me.game.viewport.pos.y+~~me.game.viewport.offset.y;a.save();a.translate(-d,-g);for(var d=d-me.game.currentLevel.pos.x,g=g-me.game.currentLevel.pos.y,e=b.length,r;e--,r=b[e];){for(var h=c.length,k;h--,k=c[h];)if(!me.sys.dirtyRegion||!k.isSprite||k.overlaps(r))!0===k.floating&&(a.save(),a.translate(d,g)),k.draw(a,r),
!0===k.floating&&a.restore(),f++;me.debug.renderDirty&&r.draw(a,"white")}a.restore()};a.flush=function(){me.sys.dirtyRegion&&(b.length=0);c.length=0;a.isDirty=!1;f=0};return a}();me.game=function(){var a={},b=null,d=[],c=!1,f=null,g=null,e=function(a,b){return b.z-a.z};a.viewport=null;a.HUD=null;a.collisionMap=null;a.currentLevel=null;a.renderer=null;a.NO_OBJECT=0;a.ENEMY_OBJECT=1;a.COLLECTABLE_OBJECT=2;a.ACTION_OBJECT=3;a.onLevelLoaded=null;a.init=function(d,f){c||(d=d||me.video.getWidth(),f=f||
me.video.getHeight(),a.viewport=new me.Viewport(0,0,d,f),b=me.video.getSystemContext(),me.event.publish(me.event.GAME_INIT),c=!0)};a.reset=function(){c||a.init();a.removeAll(!0);a.viewport&&a.viewport.reset();m.reset();b.setTransform(1,0,0,1,0,0);a.currentLevel={pos:{x:0,y:0}}};a.loadTMXLevel=function(d){a.currentLevel=d;a.collisionMap=a.currentLevel.getLayerByName("collision");(!a.collisionMap||!a.collisionMap.isCollisionMap)&&console.error("WARNING : no collision map detected");for(var c=a.currentLevel.getLayers(),
f=c.length;f--;)c[f].visible&&a.add(c[f]);a.viewport.setBounds(Math.max(a.currentLevel.width,a.viewport.width),Math.max(a.currentLevel.height,a.viewport.height));c=a.currentLevel.getObjectGroups();for(f=0;f<c.length;f++)if(c[f].visible)for(var g=0;g<c[f].objects.length;g++)a.addEntity(c[f].objects[g],c[f].z);a.currentLevel.pos.x!=a.currentLevel.pos.y&&b.translate(a.currentLevel.pos.x,a.currentLevel.pos.y);a.sort();a.onLevelLoaded&&a.onLevelLoaded.call(a.onLevelLoaded,d.name);me.event.publish(me.event.LEVEL_LOADED,
[d.name])};a.add=function(a,b){a.z=b?b:a.z;d.push(a)};a.addEntity=function(b,d){var c=me.entityPool.newInstanceOf(b.name,b.x,b.y,b);c&&a.add(c,d)};a.getEntityByName=function(a){var b=[];a=a.toLowerCase();for(var c=d.length,f;c--,f=d[c];)f.name&&f.name.toLowerCase()===a&&b.push(f);return b};a.getObjectCount=function(){return d.length};a.getDrawCount=function(){return m.getDrawCount()};a.getEntityByGUID=function(a){for(var b=d.length,c;b--,c=d[b];)if(c.isEntity&&c.GUID==a)return c;return null};a.getEntityByProp=
function(a,b){for(var c=[],f=d.length,g;f--,g=d[f];)g.isEntity&&g[a]==b&&c.push(g);return c};a.addHUD=function(b,d,c,f,g){null==a.HUD&&(a.HUD=new me.HUD_Object(b,d,c,f,g),a.add(a.HUD))};a.disableHUD=function(){null!=a.HUD&&(a.remove(a.HUD),a.HUD=null)};a.update=function(){for(var b=null,c=d.length,f;c--,f=d[c];){b=me.sys.dirtyRegion&&f.isSprite?f.getRect():null;f.inViewport=f.visible&&(f.floating||f.getRect&&a.viewport.isVisible(f));var g=f.update();m.makeDirty(f,g,g?b:null)}a.viewport.update(m.isDirty)&&
m.makeAllDirty()};a.remove=function(a,b){function c(a){a.destroy&&a.destroy();m.remove(a);d.remove(a);me.entityPool.freeInstance(a)}-1<d.indexOf(a)&&(!0===b?c(a):(a.visible=!1,f=function(a){c(a);f=null}.defer(a)))};a.removeAll=function(b){f&&(clearTimeout(f),f=null);g&&(clearTimeout(g),g=null);for(var c=d.length;c--;)d[c].isPersistent||a.remove(d[c],b);!0===b&&m.flush()};a.sort=function(a){null===g&&("function"!==typeof a&&(a=e),g=function(a){d.sort(a);g=null;me.game.repaint()}.defer(a))};a.collide=
function(a,b){var c;b=!0===b?!0:!1;if(!0===b)var f=[],g=0;for(var e=d.length,h;e--,h=d[e];)if(h.inViewport&&(h.visible&&h.collidable&&h!=a)&&(c=h.collisionBox.collideVsAABB.call(h.collisionBox,a.collisionBox),0!=c.x||0!=c.y)){h.onCollision.call(h,c,a);c.type=h.type;c.obj=h;if(!b)return c;f[g++]=c}return b?f:null};a.collideType=function(a,b,c){var f;c=!0===c?!0:!1;if(!0===c)var g=[],e=0;for(var h=d.length,k;h--,k=d[h];)if(k.inViewport&&(k.visible&&k.collidable&&k.type===b&&k!=a)&&(f=k.collisionBox.collideVsAABB.call(k.collisionBox,
a.collisionBox),0!=f.x||0!=f.y)){k.onCollision.call(k,f,a);f.type=k.type;f.obj=k;if(!c)return f;g[e++]=f}return c?g:null};a.repaint=function(){m.makeAllDirty()};a.draw=function(){m.isDirty&&(m.draw(b),a.viewport.draw(b));m.flush()};return a}()})(window);
(function(e){me.Vector2d=Object.extend({x:0,y:0,init:function(a,b){this.x=a||0;this.y=b||0},set:function(a,b){this.x=a;this.y=b;return this},setZero:function(){return this.set(0,0)},setV:function(a){this.x=a.x;this.y=a.y;return this},add:function(a){this.x+=a.x;this.y+=a.y;return this},sub:function(a){this.x-=a.x;this.y-=a.y;return this},scale:function(a){this.x*=a.x;this.y*=a.y;return this},div:function(a){this.x/=a;this.y/=a;return this},abs:function(){0>this.x&&(this.x=-this.x);0>this.y&&(this.y=
-this.y);return this},clamp:function(a,b){return new me.Vector2d(this.x.clamp(a,b),this.y.clamp(a,b))},clampSelf:function(a,b){this.x=this.x.clamp(a,b);this.y=this.y.clamp(a,b);return this},minV:function(a){this.x=this.x<a.x?this.x:a.x;this.y=this.y<a.y?this.y:a.y;return this},maxV:function(a){this.x=this.x>a.x?this.x:a.x;this.y=this.y>a.y?this.y:a.y;return this},floor:function(){return new me.Vector2d(~~this.x,~~this.y)},floorSelf:function(){this.x=~~this.x;this.y=~~this.y;return this},ceil:function(){return new me.Vector2d(Math.ceil(this.x),
Math.ceil(this.y))},ceilSelf:function(){this.x=Math.ceil(this.x);this.y=Math.ceil(this.y);return this},negate:function(){return new me.Vector2d(-this.x,-this.y)},negateSelf:function(){this.x=-this.x;this.y=-this.y;return this},copy:function(a){this.x=a.x;this.y=a.y;return this},equals:function(a){return this.x===a.x&&this.y===a.y},length:function(){return Math.sqrt(this.x*this.x+this.y*this.y)},normalize:function(){var a=this.length();if(a<Number.MIN_VALUE)return 0;var b=1/a;this.x*=b;this.y*=b;return a},
dotProduct:function(a){return this.x*a.x+this.y*a.y},distance:function(a){return Math.sqrt((this.x-a.x)*(this.x-a.x)+(this.y-a.y)*(this.y-a.y))},angle:function(a){return Math.atan2(a.y-this.y,a.x-this.x)},clone:function(){return new me.Vector2d(this.x,this.y)},toString:function(){return"x:"+this.x+",y:"+this.y}});me.Rect=Object.extend({pos:null,colPos:null,anchorPoint:null,width:0,height:0,hWidth:0,hHeight:0,init:function(a,b,c){this.pos=a;this.colPos=new me.Vector2d;this.width=b;this.height=c;this.hWidth=
~~(b/2);this.hHeight=~~(c/2);this.anchorPoint=new me.Vector2d(0.5,0.5);Object.defineProperty(this,"left",{get:function(){return this.pos.x},configurable:!0});Object.defineProperty(this,"right",{get:function(){return this.pos.x+this.width},configurable:!0});Object.defineProperty(this,"top",{get:function(){return this.pos.y},configurable:!0});Object.defineProperty(this,"bottom",{get:function(){return this.pos.y+this.height},configurable:!0})},set:function(a,b,c){this.pos=a;this.width=b;this.height=
c;this.hWidth=~~(b/2);this.hHeight=~~(c/2)},getRect:function(){return new me.Rect(this.pos.clone(),this.width,this.height)},translate:function(a,b){this.pos.x+=a;this.pos.y+=b;return this},translateV:function(a){this.pos.add(a);return this},union:function(a){var b=Math.min(this.pos.x,a.pos.x),c=Math.min(this.pos.y,a.pos.y);this.width=Math.ceil(Math.max(this.pos.x+this.width,a.pos.x+a.width)-b);this.height=Math.ceil(Math.max(this.pos.y+this.height,a.pos.y+a.height)-c);this.pos.x=~~b;this.pos.y=~~c;
return this},adjustSize:function(a,b,c,d){-1!=a&&(this.colPos.x=a,this.width=b,this.hWidth=~~(this.width/2),this.left!==this.pos.x+this.colPos.x&&Object.defineProperty(this,"left",{get:function(){return this.pos.x+this.colPos.x},configurable:!0}),this.right!==this.pos.x+this.colPos.x+this.width&&Object.defineProperty(this,"right",{get:function(){return this.pos.x+this.colPos.x+this.width},configurable:!0}));-1!=c&&(this.colPos.y=c,this.height=d,this.hHeight=~~(this.height/2),this.top!==this.pos.y+
this.colPos.y&&Object.defineProperty(this,"top",{get:function(){return this.pos.y+this.colPos.y},configurable:!0}),this.bottom!==this.pos.y+this.colPos.y+this.height&&Object.defineProperty(this,"bottom",{get:function(){return this.pos.y+this.colPos.y+this.height},configurable:!0}))},flipX:function(a){this.colPos.x=a-this.width-this.colPos.x;this.hWidth=~~(this.width/2)},flipY:function(a){this.colPos.y=a-this.height-this.colPos.y;this.hHeight=~~(this.height/2)},equals:function(a){return this.left===
a.left&&this.right===a.right&&this.top===a.top&&this.bottom===a.bottom},overlaps:function(a){return this.left<a.right&&a.left<this.right&&this.top<a.bottom&&a.top<this.bottom},within:function(a){return a.left<=this.left&&a.right>=this.right&&a.top<=this.top&&a.bottom>=this.bottom},contains:function(a){return a.left>=this.left&&a.right<=this.right&&a.top>=this.top&&a.bottom<=this.bottom},containsPoint:function(a){return a.x>=this.left&&a.x<=this.right&&a.y>=this.top&&a.y<=this.bottom},collideVsAABB:function(a){var b=
new me.Vector2d(0,0);if(this.overlaps(a)){var c=this.left+this.hWidth-a.left-a.hWidth,d=this.top+this.hHeight-a.top-a.hHeight;b.x=a.hWidth+this.hWidth-(0>c?-c:c);b.y=a.hHeight+this.hHeight-(0>d?-d:d);b.x<b.y?(b.y=0,b.x=0>c?-b.x:b.x):(b.x=0,b.y=0>d?-b.y:b.y)}return b},draw:function(a,b){a.strokeStyle=b||"red";a.strokeRect(this.left,this.top,this.width,this.height)}})})(window);(function(e){me.debug={displayFPS:!1,renderHitBox:!1,renderCollisionMap:!1,renderDirty:!1,renderVelocity:!1}})(window);
(function(e){me.Renderable=me.Rect.extend({isRenderable:!0,visible:!0,inViewport:!1,isPersistent:!1,floating:!1,init:function(a,b,c){this.parent(a,b,c)},update:function(){return!1},draw:function(a,b){this.parent(a,b)}})})(window);
(function(e){var a=2*Math.PI;me.SpriteObject=me.Renderable.extend({scale:null,scaleFlag:!1,lastflipX:!1,lastflipY:!1,z:0,offset:null,angle:0,alpha:1,image:null,flickering:!1,flickerTimer:-1,flickercb:null,flickerState:!1,init:function(a,c,d,f,g){this.isSprite=!0;this.parent(new me.Vector2d(a,c),f||d.width,g||d.height);this.image=d;this.scale=new me.Vector2d(1,1);this.scaleFlag=this.lastflipX=this.lastflipY=!1;this.offset=new me.Vector2d(0,0);this.alpha=1;this.visible=!0;this.flickering=this.isPersistent=
!1},setTransparency:function(a){a="#"==a.charAt(0)?a.substring(1,7):a;this.image=me.video.applyRGBFilter(this.image,"transparent",a.toUpperCase()).canvas},isFlickering:function(){return this.flickering},flicker:function(a,c){this.flickerTimer=a;0>this.flickerTimer?(this.flickering=!1,this.flickercb=null):this.flickering||(this.flickercb=c,this.flickering=!0)},flipX:function(a){a!=this.lastflipX&&(this.lastflipX=a,this.scale.x=-this.scale.x,this.scaleFlag=1!=this.scale.x||1!=this.scale.y)},flipY:function(a){a!=
this.lastflipY&&(this.lastflipY=a,this.scale.y=-this.scale.y,this.scaleFlag=1!=this.scale.x||1!=this.scale.y)},resize:function(a){0<a&&(this.scale.x=0>this.scale.x?-a:a,this.scale.y=0>this.scale.y?-a:a,this.scaleFlag=1!=this.scale.x||1!=this.scale.y)},getOpacity:function(){return this.alpha},setOpacity:function(a){"number"===typeof a&&(this.alpha=a.clamp(0,1))},update:function(){return this.flickering?(this.flickerTimer-=me.timer.tick,0>this.flickerTimer&&(this.flickercb&&this.flickercb(),this.flicker(-1)),
!0):!1},draw:function(a){if(this.flickering&&(this.flickerState=!this.flickerState,!this.flickerState))return;a.save();a.globalAlpha=this.alpha;var c=~~this.pos.x,d=~~this.pos.y;if(this.scaleFlag||0!==this.angle){var f=this.width*this.anchorPoint.x,g=this.height*this.anchorPoint.y;a.translate(c+f,d+g);this.scaleFlag&&a.scale(this.scale.x,this.scale.y);0!==this.angle&&a.rotate(this.angle);c=-f;d=-g}a.drawImage(this.image,this.offset.x,this.offset.y,this.width,this.height,c,d,this.width,this.height);
a.restore();me.debug.renderHitBox&&this.parent(a,"green")},destroy:function(){this.onDestroyEvent.apply(this,arguments)},onDestroyEvent:function(){}});me.AnimationSheet=me.SpriteObject.extend({fpscount:0,spacing:0,margin:0,animationpause:!1,animationspeed:0,init:function(a,c,d,f,g,e,h,l){this.anim=[];this.current=this.resetAnim=null;this.animationspeed=me.sys.fps/10;this.spritecount=null;this.spacing=e||0;this.margin=h||0;this.defaultAngle=0;this.parent(a,c,d,f,g,e,h);this.textureAtlas=null;this.buildLocalAtlas(l||
void 0);this.addAnimation("default",null);this.setCurrentAnimation("default")},buildLocalAtlas:function(a){if(void 0!==a)this.textureAtlas=a,this.spritecount=new me.Vector2d(this.textureAtlas.length,1);else{this.textureAtlas=[];this.spritecount=new me.Vector2d(~~((this.image.width-this.margin)/(this.width+this.spacing)),~~((this.image.height-this.margin)/(this.height+this.spacing)));1==this.spritecount.x*this.spritecount.y&&(this.setAnimationFrame=function(){});a=0;for(var c=this.spritecount.x*this.spritecount.y;a<
c;a++)this.textureAtlas[a]={offset:new me.Vector2d(this.margin+(this.spacing+this.width)*(a%this.spritecount.x),this.margin+(this.spacing+this.height)*~~(a/this.spritecount.x)),width:this.width,height:this.height,angle:0}}},addAnimation:function(a,c,d){this.anim[a]={name:a,frame:[],idx:0,length:0,animationspeed:d||this.animationspeed};if(null==c){c=[];d=0;for(var f=this.spritecount.x*this.spritecount.y;d<f;d++)c[d]=d}d=0;for(f=c.length;d<f;d++)this.anim[a].frame[d]=this.textureAtlas[c[d]];this.anim[a].length=
this.anim[a].frame.length},setCurrentAnimation:function(a,c){if(this.anim[a])this.current=this.anim[a],this.resetAnim=c||null,this.setAnimationFrame(this.current.idx);else throw"melonJS: animation id '"+a+"' not defined";},isCurrentAnimation:function(a){return this.current.name==a},setAnimationFrame:function(b){this.current.idx=(b||0)%this.current.length;b=this.current.frame[this.current.idx];this.offset=b.offset;this.width=b.width;this.height=b.height;this.defaultAngle!==b.angle&&(this.angle=(this.angle+
b.angle-this.defaultAngle)%a,this.defaultAngle=b.angle)},getCurrentAnimationFrame:function(){return this.current.idx},update:function(){return this.visible&&!this.animationpause&&this.fpscount++>this.current.animationspeed?(this.setAnimationFrame(++this.current.idx),this.fpscount=0,0==this.current.idx&&this.resetAnim&&("string"==typeof this.resetAnim?this.setCurrentAnimation(this.resetAnim):"function"==typeof this.resetAnim&&this.resetAnim()),this.parent()||!0):this.parent()}})})(window);
(function(e){me.TextureAtlas=Object.extend({format:null,texture:null,atlas:null,init:function(a,b){if(a&&a.meta&&a.meta.app.contains("texturepacker")){this.format="texturepacker";if(void 0===b){var c=me.utils.getBasename(a.meta.image);this.texture=me.loader.getImage(c);if(null===this.texture)throw"melonjs: Atlas texture '"+c+"' not found";}else this.texture=b;this.atlas=this.initFromTexturePacker(a)}if(null===this.atlas)throw"melonjs: texture atlas format not supported";},initFromTexturePacker:function(a){var b=
{};a.frames.forEach(function(a){if(!0===a.rotated)var d=a.frame.h,f=a.frame.w;else d=a.frame.w,f=a.frame.h;b[a.filename]={frame:new me.Rect(new me.Vector2d(a.frame.x,a.frame.y),d,f),source:new me.Rect(new me.Vector2d(a.spriteSourceSize.x,a.spriteSourceSize.y),a.spriteSourceSize.w,a.spriteSourceSize.h),rotated:!0===a.rotated,trimmed:!0===a.trimmed}});return b},createSpriteFromName:function(a){if(a=this.atlas[a]){var b=new me.SpriteObject(0,0,this.texture,a.frame.width,a.frame.height);b.offset.setV(a.frame.pos);
!0===a.rotated&&(b.angle=-(Math.PI/2));return b}throw"melonjs: TextureAtlas - region not found";},createAnimationFromName:function(a){for(var b=[],c=0,d=0;d<a.length;++d){var f=this.atlas[a[d]];if(f)b[c++]={pos:f.source.pos.clone(),offset:f.frame.pos.clone(),width:f.frame.width,height:f.frame.height,angle:!0===f.rotated?-(Math.PI/2):0};else throw"melonjs: TextureAtlas - region for "+a[d]+" not found";}return new me.AnimationSheet(0,0,this.texture,0,0,0,0,b)}})})(window);
(function(e){var a=Math.min,b=Math.max;me.Viewport=me.Rect.extend({AXIS:{NONE:0,HORIZONTAL:1,VERTICAL:2,BOTH:3},limits:null,target:null,follow_axis:0,shaking:!1,_shake:null,_fadeIn:null,_fadeOut:null,_deadwidth:0,_deadheight:0,_limitwidth:0,_limitheight:0,init:function(a,b,f,g,e,h){this.parent(new me.Vector2d(a,b),f-a,g-b);this.limits=new me.Vector2d(e||this.width,h||this.height);this.offset=new me.Vector2d;this.target=null;this.follow_axis=this.AXIS.NONE;this._shake={intensity:0,duration:0,axis:this.AXIS.BOTH,
onComplete:null,start:0};this._fadeOut={color:0,alpha:0,duration:0,tween:null};this._fadeIn={color:0,alpha:1,duration:0,tween:null};this.setDeadzone(this.width/6,this.height/6)},_followH:function(c){return c.x-this.pos.x>this._deadwidth?(this.pos.x=~~a(c.x-this._deadwidth,this._limitwidth),!0):c.x-this.pos.x<this.deadzone.x?(this.pos.x=~~b(c.x-this.deadzone.x,0),!0):!1},_followV:function(c){return c.y-this.pos.y>this._deadheight?(this.pos.y=~~a(c.y-this._deadheight,this._limitheight),!0):c.y-this.pos.y<
this.deadzone.y?(this.pos.y=~~b(c.y-this.deadzone.y,0),!0):!1},reset:function(a,b){this.pos.x=a||0;this.pos.y=b||0;this.follow_axis=this.target=null},setDeadzone:function(a,b){this.deadzone=new me.Vector2d(~~((this.width-a)/2),~~((this.height-b)/2-0.25*b));this._deadwidth=this.width-this.deadzone.x;this._deadheight=this.height-this.deadzone.y;this.update(!0)},setBounds:function(a,b){this.limits.set(a,b);this._limitwidth=this.limits.x-this.width;this._limitheight=this.limits.y-this.height},follow:function(a,
b){if(a instanceof me.ObjectEntity)this.target=a.pos;else if(a instanceof me.Vector2d)this.target=a;else throw"melonJS: invalid target for viewport.follow";this.follow_axis=b||this.AXIS.BOTH;this.update(!0)},move:function(a,b){var f=~~(this.pos.y+b);this.pos.x=(~~(this.pos.x+a)).clamp(0,this._limitwidth);this.pos.y=f.clamp(0,this._limitheight)},update:function(a){if(this.target&&a)switch(this.follow_axis){case this.AXIS.HORIZONTAL:a=this._followH(this.target);break;case this.AXIS.VERTICAL:a=this._followV(this.target);
break;case this.AXIS.BOTH:a=this._followH(this.target),a=this._followV(this.target)||a}if(this.shaking){if(me.timer.getTime()-this._shake.start>=this._shake.duration){if(this.shaking=!1,this.offset.setZero(),"function"===typeof this._shake.onComplete)this._shake.onComplete()}else{if(this._shake.axis==this.AXIS.BOTH||this._shake.axis==this.AXIS.HORIZONTAL)this.offset.x=(Math.random()-0.5)*this._shake.intensity;if(this._shake.axis==this.AXIS.BOTH||this._shake.axis==this.AXIS.VERTICAL)this.offset.y=
(Math.random()-0.5)*this._shake.intensity}a=!0}if(null!=this._fadeIn.tween||null!=this._fadeOut.tween)a=!0;return a},shake:function(a,b,f,g){this.shaking=!0;this._shake={intensity:a,duration:b,axis:f||this.AXIS.BOTH,onComplete:g||null,start:me.timer.getTime()}},fadeOut:function(a,b,f){this._fadeOut.color=a;this._fadeOut.duration=b||1E3;this._fadeOut.alpha=1;this._fadeOut.tween=(new me.Tween(this._fadeOut)).to({alpha:0},this._fadeOut.duration).onComplete(f||null);this._fadeOut.tween.start()},fadeIn:function(a,
b,f){this._fadeIn.color=a;this._fadeIn.duration=b||1E3;this._fadeIn.alpha=0;this._fadeIn.tween=(new me.Tween(this._fadeIn)).to({alpha:1},this._fadeIn.duration).onComplete(f||null);this._fadeIn.tween.start()},getWidth:function(){return this.width},getHeight:function(){return this.height},focusOn:function(a){this.pos.x=a.x-0.5*this.width;this.pos.y=a.y-0.5*this.height},isVisible:function(a){return a.overlaps(this)},draw:function(a){this._fadeIn.tween&&(a.globalAlpha=this._fadeIn.alpha,me.video.clearSurface(a,
me.utils.HexToRGB(this._fadeIn.color)),a.globalAlpha=1,1==this._fadeIn.alpha&&(this._fadeIn.tween=null));this._fadeOut.tween&&(a.globalAlpha=this._fadeOut.alpha,me.video.clearSurface(a,me.utils.HexToRGB(this._fadeOut.color)),a.globalAlpha=1,0==this._fadeOut.alpha&&(this._fadeOut.tween=null))}})})(window);
(function(e){me.ObjectSettings={name:null,image:null,transparent_color:null,spritewidth:null,spriteheight:null,type:0,collidable:!0};me.entityPool=function(){var a={},b={};a.init=function(){a.add("me.ObjectEntity",me.ObjectEntity);a.add("me.CollectableEntity",me.CollectableEntity);a.add("me.LevelEntity",me.LevelEntity)};a.add=function(a,d,f){f?b[a.toLowerCase()]={"class":d,pool:[],active:[]}:b[a.toLowerCase()]=d};a.newInstanceOf=function(a){var d="string"===typeof a?a.toLowerCase():void 0;if(d&&b[d]){if(!b[d].pool){var f=
b[d];arguments[0]=f;return new (f.bind.apply(f,arguments))}var g=b[d],f=g["class"];0<g.pool.length?(f=g.pool.pop(),f.init.apply(f,Array.prototype.slice.call(arguments,1))):(arguments[0]=f,f=new (f.bind.apply(f,arguments)),f.className=d);g.active.push(f);return f}if((g=arguments[3])&&g.image)return new me.SpriteObject(g.x,g.y,g.image);d&&console.error("Cannot instantiate entity of type '"+a+"': Class not found!");return null};a.purge=function(){for(className in b)b[className].pool=[]};a.freeInstance=
function(a){var d=a.className;if(d&&b[d]){for(var f=!0,g=0,e=b[d].active.length;g<e;g++)if(b[d].active[g]===a){f=!1;b[d].active.splice(g,1);break}f||b[d].pool.push(a)}};return a}();me.ObjectEntity=me.Renderable.extend({GUID:null,type:0,collidable:!0,collisionBox:null,renderable:null,z:0,init:function(a,b,c){this.parent(new me.Vector2d(a,b),~~c.spritewidth||~~c.width,~~c.spriteheight||~~c.height);c.image&&(a="string"==typeof c.image?me.loader.getImage(c.image):c.image,this.renderable=new me.AnimationSheet(0,
0,a,~~c.spritewidth,~~c.spriteheight,~~c.spacing,~~c.margin),c.transparent_color&&this.renderable.setTransparency(c.transparent_color));this.GUID=me.utils.createGUID();this.name=c.name?c.name.toLowerCase():"";this.vel=new me.Vector2d;this.accel=new me.Vector2d;this.friction=new me.Vector2d;this.maxVel=new me.Vector2d(1E3,1E3);this.gravity=void 0!=me.sys.gravity?me.sys.gravity:0.98;this.visible=this.alive=this.isEntity=!0;this.falling=this.isPersistent=this.floating=!1;this.jumping=!0;this.slopeY=
0;this.disableTopLadderCollision=this.onladder=this.onslope=!1;this.collidable="undefined"!==typeof c.collidable?c.collidable:!0;this.type=c.type||0;this.collisionMap=me.game.collisionMap;this.collisionBox=new me.Rect(this.pos,this.width,this.height);this.canBreakTile=!1;this.onTileBreak=null},updateColRect:function(a,b,c,d){this.collisionBox.adjustSize(a,b,c,d)},onCollision:function(a,b){this.collidable&&this.type==me.game.COLLECTABLE_OBJECT&&me.game.remove(this)},setVelocity:function(a,b){this.accel.x=
0!=a?a:this.accel.x;this.accel.y=0!=b?b:this.accel.y;this.setMaxVelocity(a,b)},setMaxVelocity:function(a,b){this.maxVel.x=a;this.maxVel.y=b},setFriction:function(a,b){this.friction.x=a||0;this.friction.y=b||0},flipX:function(a){a!=this.lastflipX&&(this.renderable&&this.renderable.flipX(a),this.collisionBox.flipX(this.width))},flipY:function(a){a!=this.lastflipY&&(this.renderable&&this.renderable.flipY(a),this.collisionBox.flipY(this.height))},doWalk:function(a){this.flipX(a);this.vel.x+=a?-this.accel.x*
me.timer.tick:this.accel.x*me.timer.tick},doClimb:function(a){return this.onladder?(this.vel.y=a?-this.accel.x*me.timer.tick:this.accel.x*me.timer.tick,this.disableTopLadderCollision=!a,!0):!1},doJump:function(){return!this.jumping&&!this.falling?(this.vel.y=-this.maxVel.y*me.timer.tick,this.jumping=!0):!1},forceJump:function(){this.jumping=this.falling=!1;this.doJump()},distanceTo:function(a){var b=this.pos.x+this.hWidth-(a.pos.x+a.hWidth);a=this.pos.y+this.hHeight-(a.pos.y+a.hHeight);return Math.sqrt(b*
b+a*a)},distanceToPoint:function(a){var b=this.pos.x+this.hWidth-a.x;a=this.pos.y+this.hHeight-a.y;return Math.sqrt(b*b+a*a)},angleTo:function(a){return Math.atan2(a.pos.y+a.hHeight-(this.pos.y+this.hHeight),a.pos.x+a.hWidth-(this.pos.x+this.hWidth))},angleToPoint:function(a){return Math.atan2(a.y-(this.pos.y+this.hHeight),a.x-(this.pos.x+this.hWidth))},checkSlope:function(a,b){this.pos.y=a.pos.y-this.height;this.slopeY=b?a.height-(this.collisionBox.right+this.vel.x-a.pos.x):this.collisionBox.left+
this.vel.x-a.pos.x;this.vel.y=0;this.pos.y+=this.slopeY.clamp(0,a.height)},computeVelocity:function(a){this.gravity&&(a.y+=!this.onladder?this.gravity*me.timer.tick:0,this.jumping=(this.falling=0<a.y)?!1:this.jumping);this.friction.x&&(a.x=me.utils.applyFriction(a.x,this.friction.x));this.friction.y&&(a.y=me.utils.applyFriction(a.y,this.friction.y));0!=a.y&&(a.y=a.y.clamp(-this.maxVel.y,this.maxVel.y));0!=a.x&&(a.x=a.x.clamp(-this.maxVel.x,this.maxVel.x))},updateMovement:function(){this.computeVelocity(this.vel);
if(this.collidable){var a=this.collisionMap.checkCollision(this.collisionBox,this.vel);this.onslope=a.yprop.isSlope||a.xprop.isSlope;this.onladder=!1;if(a.y)if(this.onladder=a.yprop.isLadder||a.yprop.isTopLadder,0<a.y)if(a.yprop.isSolid||a.yprop.isPlatform&&this.collisionBox.bottom-1<=a.ytile.pos.y||a.yprop.isTopLadder&&!this.disableTopLadderCollision)this.pos.y=~~this.pos.y,this.vel.y=this.falling?a.ytile.pos.y-this.collisionBox.bottom:0,this.falling=!1;else if(a.yprop.isSlope&&!this.jumping)this.checkSlope(a.ytile,
a.yprop.isLeftSlope),this.falling=!1;else{if(a.yprop.isBreakable)if(this.canBreakTile){if(me.game.currentLevel.clearTile(a.ytile.col,a.ytile.row),this.onTileBreak)this.onTileBreak()}else this.pos.y=~~this.pos.y,this.vel.y=this.falling?a.ytile.pos.y-this.collisionBox.bottom:0,this.falling=!1}else 0>a.y&&(!a.yprop.isPlatform&&!a.yprop.isLadder&&!a.yprop.isTopLadder)&&(this.falling=!0,this.vel.y=0);if(a.x)if(this.onladder=a.xprop.isLadder||a.yprop.isTopLadder,a.xprop.isSlope&&!this.jumping)this.checkSlope(a.xtile,
a.xprop.isLeftSlope),this.falling=!1;else if(!a.xprop.isPlatform&&!a.xprop.isLadder&&!a.xprop.isTopLadder)if(a.xprop.isBreakable&&this.canBreakTile){if(me.game.currentLevel.clearTile(a.xtile.col,a.xtile.row),this.onTileBreak)this.onTileBreak()}else this.vel.x=0}this.pos.add(this.vel);return a},collide:function(a){return me.game.collide(this,a||!1)},collideType:function(a,b){return me.game.collideType(this,a,b||!1)},update:function(){return this.renderable?this.renderable.update():!1},getRect:function(){return this.renderable?
this.renderable.getRect().translateV(this.pos):null},draw:function(a){if(this.renderable){var b=~~(this.pos.x+this.anchorPoint.x*(this.width-this.renderable.width)),c=~~(this.pos.y+this.anchorPoint.y*(this.height-this.renderable.height));a.translate(b,c);this.renderable.draw(a);a.translate(-b,-c)}me.debug.renderHitBox&&this.collisionBox&&(this.collisionBox.draw(a,"red"),b=~~(this.pos.x+this.hWidth),c=~~(this.pos.y+this.hHeight),a.lineWidth=1,a.beginPath(),a.moveTo(b,c),a.lineTo(b+~~(this.vel.x*this.hWidth),
c+~~(this.vel.y*this.hHeight)),a.stroke())},destroy:function(){this.renderable&&(this.renderable.destroy.apply(this.renderable,arguments),this.renderable=null);this.onDestroyEvent.apply(this,arguments);this.collisionBox=this.pos=null},onDestroyEvent:function(){}});me.CollectableEntity=me.ObjectEntity.extend({init:function(a,b,c){this.parent(a,b,c);this.type=me.game.COLLECTABLE_OBJECT}});me.LevelEntity=me.ObjectEntity.extend({init:function(a,b,c){this.parent(a,b,c);this.nextlevel=c.to;this.fade=c.fade;
this.duration=c.duration;this.fading=!1;this.gotolevel=c.to},onFadeComplete:function(){me.levelDirector.loadLevel(this.gotolevel);me.game.viewport.fadeOut(this.fade,this.duration)},goTo:function(a){this.gotolevel=a||this.nextlevel;this.fade&&this.duration?this.fading||(this.fading=!0,me.game.viewport.fadeIn(this.fade,this.duration,this.onFadeComplete.bind(this))):me.levelDirector.loadLevel(this.gotolevel)},onCollision:function(){this.goTo()}})})(window);
(function(e){me.ScreenObject=me.Renderable.extend({addAsObject:!1,z:999,init:function(a,b){this.parent(new me.Vector2d(0,0),0,0);this.isPersistent=(this.addAsObject=this.visible=!0===a||!1)&&!0===b||!1},reset:function(){me.game.reset();this.onResetEvent.apply(this,arguments);this.addAsObject&&(this.visible=!0,this.set(me.game.viewport.pos,me.game.viewport.width,me.game.viewport.height),me.game.add(this,this.z));me.game.sort()},destroy:function(){this.onDestroyEvent.apply(this,arguments)},update:function(){return!1},
onUpdateFrame:function(){me.timer.update();me.game.update();me.game.draw();me.video.blitSurface()},draw:function(){},onResetEvent:function(){},onDestroyEvent:function(){}});me.state=function(){function a(){if(-1==l&&-1==m){me.timer.reset();if(me.sys.useNativeAnimFrame){m=window.requestAnimationFrame(b);if(-1!=m)return;me.sys.useNativeAnimFrame=!1}l=setInterval(s,~~(1E3/me.sys.fps))}}function b(){s();-1!=m&&(m=window.requestAnimationFrame(b))}function c(){-1!=l&&(clearInterval(l),l=-1);-1!=m&&(window.cancelAnimationFrame(m),
m=-1)}function d(b){c();p[h]&&(p[h].screen.visible&&me.game.remove.call(me.game,p[h].screen,!0),p[h].screen.destroy());p[b]&&(h=b,p[h].screen.reset.apply(p[h].screen,t),s=p[h].screen.onUpdateFrame.bind(p[h].screen),a(),q&&q(),me.game.repaint())}for(var f=["ms","moz","webkit","o"],g=0;g<f.length&&!window.requestAnimationFrame;++g)window.requestAnimationFrame=window[f[g]+"RequestAnimationFrame"],window.cancelAnimationFrame=window[f[g]+"CancelAnimationFrame"]||window[f[g]+"CancelRequestAnimationFrame"];
window.requestAnimationFrame||(window.requestAnimationFrame=function(a,b){return-1});window.cancelAnimationFrame||(window.cancelAnimationFrame=function(){return-1});var k={},h=-1,l=-1,m=-1,p={},n="",r=0,q=null,t=null,s=null;k.LOADING=0;k.MENU=1;k.READY=2;k.PLAY=3;k.GAMEOVER=4;k.GAME_END=5;k.SCORE=6;k.CREDITS=7;k.SETTINGS=8;k.USER=100;k.onPause=null;k.onResume=null;k.init=function(){k.set(k.LOADING,me.loadingScreen);e.addEventListener("blur",function(){me.sys.pauseOnBlur&&h!=k.LOADING&&k.pause(!0);
if(k.onPause)k.onPause();me.event.publish(me.event.STATE_PAUSE)},!1);e.addEventListener("focus",function(){me.sys.pauseOnBlur&&h!=k.LOADING&&(k.resume(!0),me.game.repaint());if(k.onResume)k.onResume();me.event.publish(me.event.STATE_RESUME)},!1)};k.pause=function(a){c();a&&me.audio.pauseTrack()};k.resume=function(b){a();b&&me.audio.resumeTrack()};k.isRunning=function(){return-1!=l||-1!=m};k.set=function(a,b){p[a]={};p[a].screen=b;p[a].transition=!0};k.current=function(){return p[h].screen};k.transition=
function(a,b,d){"fade"==a&&(n=b,r=d)};k.setTransition=function(a,b){p[a].transition=b};k.change=function(a){t=null;1<arguments.length&&(t=Array.prototype.slice.call(arguments,1));r&&p[a].transition?(q=function(){me.game.viewport.fadeOut(n,r)},me.game.viewport.fadeIn(n,r,function(){d.defer(a)})):d.defer(a)};k.isCurrent=function(a){return h==a};return k}()})(window);
(function(e){me.DefaultLoadingScreen=me.ScreenObject.extend({init:function(){this.parent(!0);this.invalidate=!1;this.handle=null},onResetEvent:function(){this.logo1=new me.Font("century gothic",32,"white","middle");this.logo2=new me.Font("century gothic",32,"#89b002","middle");this.logo2.bold();this.logo1.textBaseline=this.logo2.textBaseline="alphabetic";this.handle=me.event.subscribe(me.event.LOADER_PROGRESS,this.onProgressUpdate.bind(this));this.loadPercent=0},onDestroyEvent:function(){this.logo1=
this.logo2=null;this.handle&&(me.event.unsubscribe(this.handle),this.handle=null)},onProgressUpdate:function(a){this.loadPercent=a;this.invalidate=!0},update:function(){return!0===this.invalidate?(this.invalidate=!1,!0):!1},draw:function(a){var b=this.logo1.measureText(a,"melon").width,c=(me.video.getWidth()-b-this.logo2.measureText(a,"JS").width)/2,d=me.video.getHeight()/2;me.video.clearSurface(a,"black");this.logo1.draw(a,"melon",c,d);this.logo2.draw(a,"JS",c+b,d);d+=this.logo1.measureText(a,"melon").height/
2;b=Math.floor(this.loadPercent*me.video.getWidth());a.strokeStyle="silver";a.strokeRect(0,d,me.video.getWidth(),6);a.fillStyle="#89b002";a.fillRect(2,d+2,b-4,2)}});me.loader=function(){function a(){p==m?f.onload?(clearTimeout(n),setTimeout(function(){f.onload();me.event.publish(me.event.LOADER_COMPLETE)},300)):console.error("no load callback defined"):n=setTimeout(a,100)}function b(a,b,d){var c=new XMLHttpRequest,f=me.utils.getFileExtension(a.src).toLowerCase();c.overrideMimeType&&("json"===f?c.overrideMimeType("application/json"):
c.overrideMimeType("text/xml"));c.open("GET",a.src+me.nocache,!0);c.ontimeout=d;c.onreadystatechange=function(){if(4==c.readyState)if(200==c.status||0==c.status&&c.responseText){var g=null;switch(f){case "xml":case "tmx":g=me.sys.ua.match(/msie/i)||!c.responseXML?(new DOMParser).parseFromString(c.responseText,"text/xml"):c.responseXML;f="xml";break;case "json":g=JSON.parse(c.responseText);break;default:throw"melonJS: TMX file format "+f+"not supported !";}e[a.name]={data:g,isTMX:"tmx"===a.type,format:f};
"tmx"===a.type&&me.levelDirector.addTMXLevel(a.name);b()}else d()};c.send(null)}function c(a,b,d){var c=new XMLHttpRequest;c.overrideMimeType&&c.overrideMimeType("application/json");c.open("GET",a.src+me.nocache,!0);c.ontimeout=d;c.onreadystatechange=function(){4==c.readyState&&(200==c.status||0==c.status&&c.responseText?(l[a.name]=JSON.parse(c.responseText),b()):d())};c.send(null)}function d(a,b,d){var c=new XMLHttpRequest;c.open("GET",a.src+me.nocache,!1);c.responseType="arraybuffer";c.onerror=
d;c.onload=function(d){if(d=c.response){d=new Uint8Array(d);var f=[];h[a.name]=new dataType;for(var g=0;g<d.byteLength;g++)f[g]=String.fromCharCode(d[g]);h[a.name].data=f.join("");b()}};c.send()}var f={},g={},e={},h={},l={},m=0,p=0,n=0;f.onload=void 0;f.onProgress=void 0;f.onResourceLoaded=function(a){p++;a=f.getLoadProgress();if(f.onProgress)f.onProgress(a);me.event.publish(me.event.LOADER_PROGRESS,[a])};f.onLoadingError=function(a){throw"melonJS: Failed loading resource "+a.src;};f.preload=function(b){for(var d=
0;d<b.length;d++)m+=f.load(b[d],f.onResourceLoaded.bind(f),f.onLoadingError.bind(f,b[d]));a()};f.load=function(a,f,e){a.name=a.name.toLowerCase();switch(a.type){case "binary":return d.call(this,a,f,e),1;case "image":return g[a.name]=new Image,g[a.name].onload=f,g[a.name].onerror=e,g[a.name].src=a.src+me.nocache,1;case "tps":return c.call(this,a,f,e),1;case "tmx":case "tsx":return b.call(this,a,f,e),1;case "audio":if(me.audio.isAudioEnable())return me.audio.load(a,f,e),1;break;default:throw"melonJS: me.loader.load : unknown or invalid resource type : "+
a.type;}return 0};f.unload=function(a){a.name=a.name.toLowerCase();switch(a.type){case "binary":if(!(a.name in h))return!1;delete h[a.name];return!0;case "image":if(!(a.name in g))return!1;delete g[a.name];return!0;case "tps":if(!(a.name in l))return!1;delete l[a.name];return!0;case "tmx":case "tsx":if(!(a.name in e))return!1;delete e[a.name];return!0;case "audio":return me.audio.unload(a.name);default:throw"melonJS: me.loader.unload : unknown or invalid resource type : "+a.type;}};f.unloadAll=function(){for(var a in h)f.unload(a);
for(a in g)f.unload(a);for(a in e)f.unload(a);for(a in l)f.unload(a);me.audio.unloadAll()};f.getTMXFormat=function(a){a=a.toLowerCase();return a in e?e[a].format:null};f.getTMX=function(a){a=a.toLowerCase();return a in e?e[a].data:null};f.getBinary=function(a){a=a.toLowerCase();return a in h?h[a]:null};f.getAtlas=function(a){a=a.toLowerCase();return a in l?l[a]:null};f.getImage=function(a){a=a.toLowerCase();if(a in g){if(!0===me.sys.cacheImage){var b=me.video.createCanvasSurface(g[a].width,g[a].height);
b.drawImage(g[a],0,0);return b.canvas}return g[a]}return null};f.getLoadProgress=function(){return p/m};return f}()})(window);
(function(e){me.Font=Object.extend({font:null,height:null,color:null,textAlign:"left",textBaseline:"top",lineHeight:1,init:function(a,b,c,d){this.set(a,b,c,d)},bold:function(){this.font="bold "+this.font},italic:function(){this.font="italic "+this.font},set:function(a,b,c,d){a=a.split(",");for(var f=0;f<a.length;f++)a[f]="'"+a[f]+"'";this.height=parseInt(b);"number"===typeof b&&(b=""+b+"px");this.font=b+" "+a.join(",");this.color=c;d&&(this.textAlign=d)},getRect:function(){return new me.Rect(new Vector2d(0,
0),0,0)},measureText:function(a,b){a.font=this.font;a.fillStyle=this.color;a.textAlign=this.textAlign;a.textBaseline=this.textBaseline;for(var c=(""+b).split("\n"),d=0,f=0,g=0;g<c.length;g++)d=Math.max(a.measureText(c[g].trim()).width,d),f+=this.height*this.lineHeight;return{width:d,height:f}},draw:function(a,b,c,d){a.font=this.font;a.fillStyle=this.color;a.textAlign=this.textAlign;a.textBaseline=this.textBaseline;b=(""+b).split("\n");for(var f=0;f<b.length;f++)a.fillText(b[f].trim(),~~c,~~d),d+=
this.height*this.lineHeight}});me.BitmapFont=me.Font.extend({size:null,sSize:null,firstChar:32,charCount:0,init:function(a,b,c,d){this.parent(a,null,null);this.size=new me.Vector2d;this.sSize=new me.Vector2d;this.firstChar=d||32;this.loadFontMetrics(a,b);this.textAlign="left";this.textBaseline="top";c&&this.resize(c)},loadFontMetrics:function(a,b){this.font=me.loader.getImage(a);this.size.x=b.x||b;this.size.y=b.y||this.font.height;this.sSize.copy(this.size);this.charCount=~~(this.font.width/this.size.x)},
set:function(a,b){this.textAlign=a;b&&this.resize(b)},resize:function(a){this.sSize.setV(this.size);this.sSize.x*=a;this.sSize.y*=a},measureText:function(a,b){for(var c=(""+b).split("\n"),d=0,f=0,g=0;g<c.length;g++)d=Math.max(c[g].trim().length*this.sSize.x,d),f+=this.sSize.y*this.lineHeight;return{width:d,height:f}},draw:function(a,b,c,d){b=(""+b).split("\n");for(var f=c,g=this.sSize.y*this.lineHeight,e=0;e<b.length;e++){c=f;var h=b[e].trim(),l=h.length*this.sSize.x;switch(this.textAlign){case "right":c-=
l;break;case "center":c-=0.5*l}switch(this.textBaseline){case "middle":d-=0.5*g;break;case "ideographic":case "alphabetic":case "bottom":d-=g}for(var l=0,m=h.length;l<m;l++){var p=h.charCodeAt(l)-this.firstChar;a.drawImage(this.font,this.size.x*(p%this.charCount),this.size.y*~~(p/this.charCount),this.size.x,this.size.y,~~c,~~d,this.sSize.x,this.sSize.y);c+=this.sSize.x}d+=g}}})})(window);
(function(e){me.GUI_Object=me.SpriteObject.extend({isClickable:!0,updated:!1,init:function(a,b,c){this.parent(a,b,"string"==typeof c.image?me.loader.getImage(c.image):c.image,c.spritewidth,c.spriteheight);this.floating=!0;me.input.registerMouseEvent("mousedown",this,this.clicked.bind(this))},update:function(){return this.updated?(this.updated=!1,!0):!1},clicked:function(){if(this.isClickable)return this.updated=!0,this.onClick()},onClick:function(){return!0},onDestroyEvent:function(){me.input.releaseMouseEvent("mousedown",
this)}})})(window);
(function(e){me.HUD_Item=Object.extend({init:function(a,b,c){this.pos=new me.Vector2d(a||0,b||0);this.visible=!0;this.defaultvalue=c||0;this.value=c||0;this.updated=!0},reset:function(){this.set(this.defaultvalue)},set:function(a){this.value=a;return this.updated=!0},update:function(a){return this.set(this.value+a)},draw:function(a,b,c){}});me.HUD_Object=me.Renderable.extend({init:function(a,b,c,d,f){this.parent(new me.Vector2d(a||0,b||0),c||me.video.getWidth(),d||me.video.getHeight());this.bgcolor=
f;this.HUDItems={};this.HUDobj=[];this.objCount=0;this.HUD_invalidated=this.floating=this.visible=!0;this.HUDCanvas=me.video.createCanvas(this.width,this.height);this.HUDCanvasSurface=this.HUDCanvas.getContext("2d");this.z=999;this.isPersistent=!0},addItem:function(a,b){this.HUDItems[a]=b;this.HUDobj.push(this.HUDItems[a]);this.objCount++;this.HUD_invalidated=!0},removeItem:function(a){this.HUDItems[a]&&(this.HUDobj.splice(this.HUDobj.indexOf(this.HUDItems[a]),1),this.HUDItems[a]=null,this.objCount--,
this.HUD_invalidated=!0)},setItemValue:function(a,b){this.HUDItems[a]&&!0==this.HUDItems[a].set(b)&&(this.HUD_invalidated=!0)},updateItemValue:function(a,b){this.HUDItems[a]&&!0==this.HUDItems[a].update(b)&&(this.HUD_invalidated=!0)},getItemValue:function(a){return this.HUDItems[a]?this.HUDItems[a].value:0},update:function(){return this.HUD_invalidated},reset:function(a){void 0!=a?(this.HUDItems[a]&&this.HUDItems[a].reset(),this.HUD_invalidated=!0):this.resetAll()},resetAll:function(){for(var a=this.objCount,
b;a--,b=this.HUDobj[a];)b.reset();this.HUD_invalidated=!0},draw:function(a){if(this.HUD_invalidated){this.bgcolor?me.video.clearSurface(this.HUDCanvasSurface,this.bgcolor):this.HUDCanvas.width=this.HUDCanvas.width;for(var b=this.objCount,c;b--,c=this.HUDobj[b];)c.visible&&(c.draw(this.HUDCanvasSurface,0,0),c.updated&&(c.updated=!1))}a.drawImage(this.HUDCanvas,this.pos.x,this.pos.y);this.HUD_invalidated=!1}})})(window);
(function(e){me.audio=function(){function a(a){a=e[a];for(var b=0,d;d=a[b++];)if(d.ended||!d.currentTime)return d.currentTime=n,d;a[0].pause();a[0].currentTime=n;return a[0]}function b(a,b){if(3<r++){var d="melonJS: failed loading "+a+"."+h;if(!1===me.sys.stopOnAudioError)me.audio.disable(),b&&b(),console.log(d+", disabling audio");else throw d;}else e[a][0].load()}function c(a,b,d){r=0;if(1<b)for(var c=e[a][0],f=1;f<b;f++)e[a][f]=new Audio(c.src),e[a][f].preload="auto",e[a][f].load();d&&d()}function d(b,
d,c,f){var e=a(b.toLowerCase());e.loop=d||!1;e.volume=f?parseFloat(f).clamp(0,1):q.volume;e.muted=q.muted;e.play();c&&!d&&e.addEventListener("ended",function(a){e.removeEventListener("ended",arguments.callee,!1);c()},!1);return e}function f(a,b,d){d&&!b&&setTimeout(d,2E3);return null}var g={},e={},h=-1,l=null,m=null,p=!0,n=0,r=0,q={volume:1,muted:!1},t=!1,s=[];g.capabilities={mp3:{codec:"audio/mpeg",canPlay:!1,canPlayType:"no"},ogg:{codec:'audio/ogg; codecs="vorbis"',canPlay:!1,canPlayType:"no"},
m4a:{codec:'audio/mp4; codecs="mp4a.40.2"',canPlay:!1,canPlayType:"no"},wav:{codec:'audio/wav; codecs="1"',canPlay:!1,canPlayType:"no"}};g.detectCapabilities=function(){var a=document.createElement("audio");if(a.canPlayType)for(var b in g.capabilities){var d=a.canPlayType(g.capabilities[b].codec);""!==d&&"no"!==d&&(g.capabilities[b].canPlay=!0,g.capabilities[b].canPlayType=d);me.sys.sound|=g.capabilities[b].canPlay}};g.init=function(a){if(!me.initialized)throw"melonJS: me.audio.init() called before engine initialization.";
a=new String(a?a:"mp3");a=a.split(",");var b="",c=a.length;if(me.sys.sound)for(var e="",k=0;k<c;k++)if(e=a[k].toLowerCase().trim(),g.capabilities[e]&&g.capabilities[e].canPlay&&(""===b||"probably"===g.capabilities[e].canPlayType))if(b=e,"probably"===g.capabilities[e].canPlayType)break;""===b&&(p=!1);h=b;me.sys.isMobile&&!navigator.isCocoonJS&&(p=!1);g.play=g.isAudioEnable()?d:f;return g.isAudioEnable()};g.isAudioEnable=function(){return p};g.enable=function(){p=me.sys.sound;g.play=p?d:f};g.disable=
function(){me.audio.stopTrack();g.play=f;p=!1};g.load=function(a,d,f){if(-1==h)return 0;if(me.sys.isMobile&&!navigator.isCocoonJS){if(t){s.push([a,d,f]);return}t=!0}var l=a.channel||1,n="canplaythrough";!0===a.stream&&!me.sys.isMobile&&(l=1,n="canplay");var x=new Audio(a.src+a.name+"."+h+me.nocache);x.preload="auto";x.addEventListener(n,function(b){x.removeEventListener(n,arguments.callee,!1);t=!1;c.call(me.audio,a.name,l,d);var f=s.shift();f&&g.load.apply(g,f)},!1);x.addEventListener("error",function(d){b.call(me.audio,
a.name,f)},!1);x.load();e[a.name]=[x];return 1};g.stop=function(a){if(p){a=e[a.toLowerCase()];for(var b=a.length;b--;)a[b].pause(),a[b].currentTime=n}};g.pause=function(a){if(p){a=e[a.toLowerCase()];for(var b=a.length;b--;)a[b].pause()}};g.playTrack=function(a,b){m=me.audio.play(a,!0,null,b);l=a.toLowerCase()};g.stopTrack=function(){p&&m&&(m.pause(),m=l=null)};g.setVolume=function(a){"number"===typeof a&&(q.volume=a.clamp(0,1))};g.getVolume=function(){return q.volume};g.mute=function(a,b){b=void 0===
b?!0:!!b;for(var d=e[a.toLowerCase()],c=0,f;f=d[c++];)f.muted=b};g.unmute=function(a){g.mute(a,!1)};g.muteAll=function(){q.muted=!0;for(var a in e)g.mute(a,q.muted)};g.unmuteAll=function(){q.muted=!1;for(var a in e)g.mute(a,q.muted)};g.getCurrentTrack=function(){return l};g.pauseTrack=function(){p&&m&&m.pause()};g.resumeTrack=function(){p&&m&&m.play()};g.unload=function(a){a=a.toLowerCase();if(!(a in e))return!1;l===a?g.stopTrack():g.stop(a);delete e[a];return!0};g.unloadAll=function(){for(var a in e)g.unload(a)};
return g}()})(window);
(function(e){me.timer=function(){var a={},b=null,c=0,d=0,f=0,e=0,k=0,h=Math.ceil(1E3/me.sys.fps),l=1.25*(1E3/me.sys.fps);a.tick=1;a.fps=0;a.init=function(){b=document.getElementById("framecounter");null!==b&&(me.debug.displayFPS=!0);a.reset()};a.reset=function(){e=f=Date.now();c=d=0};a.getTime=function(){return e};a.update=function(){f=e;e=Date.now();k=e-f;me.debug.displayFPS&&(c++,d+=k,0==c%10&&(this.fps=(~~(1E3*c/d)).clamp(0,me.sys.fps),c=d=0),null!==b&&b.replaceChild(document.createTextNode("("+this.fps+
"/"+me.sys.fps+" fps)"),b.firstChild));a.tick=k>l&&me.sys.interpolation?k/h:1};return a}();me.video=function(){var a={},b=null,c=null,d=null,f=null,e=null,k=-1,h=!1,l=0,m=0,p=!1,n=!0;a.init=function(k,q,t,s,u,y){if(!me.initialized)throw"melonJS: me.video.init() called before engine initialization.";h=s||!1;p="auto"===u||!1;n=void 0!==y?y:!0;u="auto"!==u?parseFloat(u||1):1;me.sys.scale=new me.Vector2d(u,u);if(p||1!==u)h=!0;l=q*me.sys.scale.x;m=t*me.sys.scale.y;window.addEventListener("resize",function(a){me.event.publish(me.event.WINDOW_ONRESIZE,
[a])},!1);window.addEventListener("orientationchange",function(a){me.event.publish(me.event.WINDOW_ONRESIZE,[a])},!1);me.event.subscribe(me.event.WINDOW_ONRESIZE,me.video.onresize.bind(me.video));b=a.createCanvas(l,m,!0);k&&(e=document.getElementById(k));e||(e=document.body);e.appendChild(b);if(!b.getContext)return!1;c=b.getContext("2d");h?(d=a.createCanvas(q,t,!1),f=d.getContext("2d")):(d=b,f=c);if(p)me.video.onresize(null);return!0};a.getWrapper=function(){return e};a.getWidth=function(){return d.width};
a.getPos=function(a){a=a||b;for(var d=new me.Vector2d(a.offsetLeft,a.offsetTop);a=a.offsetParent;)d.x+=a.offsetLeft,d.y+=a.offsetTop;return d};a.getHeight=function(){return d.height};a.createCanvas=function(a,b,c){if(0===a||0===b)throw Error("melonJS: width or height was zero, Canvas could not be initialized !");c=!0===c?navigator.isCocoonJS&&!me.sys.dirtyRegion?"screencanvas":"canvas":"canvas";c=document.createElement(c);c.width=a||d.width;c.height=b||d.height;return c};a.createCanvasSurface=function(b,
d){return a.createCanvas(b,d,!1).getContext("2d")};a.getScreenCanvas=function(){return b};a.getScreenContext=function(){return c};a.getSystemCanvas=function(){return d};a.getSystemContext=function(){return f};a.onresize=function(a){if(p){var b=me.video.getScreenCanvas().parentNode;a=b.width||window.innerWidth;b=b.height||window.innerHeight;k&&clearTimeout(k);if(n){var d=me.video.getWidth()/me.video.getHeight();a=a/b<d?a/me.video.getWidth():b/me.video.getHeight();k=me.video.updateDisplaySize.defer(a,
a)}else k=me.video.updateDisplaySize.defer(a/me.video.getWidth(),b/me.video.getHeight())}else me.input.mouse.offset=me.video.getPos()};a.updateDisplaySize=function(c,f){me.sys.scale.set(c,f);b.width=l=d.width*c;b.height=m=d.height*f;me.input.mouse.offset=me.video.getPos();a.blitSurface();k=-1};a.clearSurface=function(b,d){b.save();b.setTransform(1,0,0,1,0,0);b.fillStyle=d;b.fillRect(0,0,a.getWidth(),a.getHeight());b.restore()};a.scale=function(a,b){a.translate(-(a.canvas.width*b-a.canvas.width>>1),
-(a.canvas.height*b-a.canvas.height>>1));a.scale(b,b)};a.setImageSmoothing=function(a){for(var b=["ms","moz","webkit","o"],d=0;d<b.length;++d)void 0!==c[b[d]+"ImageSmoothingEnabled"]&&(c[b[d]+"ImageSmoothingEnabled"]=a,h&&(f[b[d]+"ImageSmoothingEnabled"]=a));c.imageSmoothingEnabled=a;h&&(f.imageSmoothingEnabled=a)};a.setAlpha=function(a,b){a.globalCompositeOperation=b?"source-over":"copy"};a.blitSurface=function(){a.blitSurface=h?function(){c.drawImage(d,0,0,d.width,d.height,0,0,l,m)}:function(){};
a.blitSurface()};a.applyRGBFilter=function(b,d,c){var f=a.createCanvasSurface(b.width,b.height,!1);b=me.utils.getPixels(b);var e=b.data;switch(d){case "b&w":d=0;for(var g=e.length;d<g;d+=4)c=3*e[d]+4*e[d+1]+e[d+2]>>>3,e[d]=c,e[d+1]=c,e[d+2]=c;break;case "brightness":c=Math.abs(c).clamp(0,1);d=0;for(g=e.length;d<g;d+=4)e[d]*=c,e[d+1]*=c,e[d+2]*=c;break;case "transparent":d=0;for(g=e.length;d<g;d+=4)me.utils.RGBToHex(e[d],e[d+1],e[d+2])===c&&(e[d+3]=0);break;default:return null}f.putImageData(b,0,0);
return f};return a}()})(window);
(function(e){me.input=function(){function a(){if(!y){n.touches.push({x:0,y:0});n.mouse.pos=new me.Vector2d(0,0);n.mouse.offset=me.video.getPos();if(me.sys.touch){me.video.getScreenCanvas().addEventListener("touchmove",h,!1);for(var a=2;a<w.length;++a)me.video.getScreenCanvas().addEventListener(w[a],m,!1)}else{me.video.getScreenCanvas().addEventListener("mousemove",h,!1);e.addEventListener("mousewheel",k,!1);for(a=2;a<v.length;++a)me.video.getScreenCanvas().addEventListener(v[a],l,!1)}y=!0}}function b(a){a.stopPropagation?
a.stopPropagation():a.cancelBubble=!0;a.preventDefault?a.preventDefault():a.returnValue=!1;return!1}function c(a,d){var c=r[d||a.keyCode||a.which];return c?(s[c]||(q[c]=!0,s[c]=t[c],me.event.publish(me.event.KEYDOWN,[c])),b(a)):!0}function d(a,d){var c=r[d||a.keyCode||a.which];return c?(q[c]=!1,s[c]=!1,me.event.publish(me.event.KEYUP,[c]),b(a)):!0}function f(a){var b=!1,d=n.mouse.handlers[a.type];if(d)for(var c=me.game.viewport.pos,f=me.game.currentLevel.pos,e=0,g=n.touches.length;e<g;e++)for(var h=
n.touches[e].x,k=n.touches[e].y,l=d.length,m;l--,m=d[l];){var p=!1===m.floating?{x:h+c.x-f.x,y:k+c.y-f.y}:{x:h,y:k};if((null===m.rect||m.rect.containsPoint(p))&&!1===m.cb(a)){b=!0;break}}return b}function g(a){n.touches.length=0;if(a.touches)for(var b=n.mouse.offset,d=0,c=a.changedTouches.length;d<c;d++){var f=a.changedTouches[d],e=f.clientX-b.x,g=f.clientY-b.y,h=me.sys.scale;if(1!=h.x||1!=h.y)e/=h.x,g/=h.y;n.touches.push({x:e,y:g,id:f.identifier})}else{var b=n.mouse.offset,e=a.pageX-b.x,g=a.pageY-
b.y,h=me.sys.scale;if(1!=h.x||1!=h.y)e/=h.x,g/=h.y;n.touches.push({x:e,y:g,id:0})}n.mouse.pos.set(n.touches[0].x,n.touches[0].y)}function k(a){return a.target==me.video.getScreenCanvas()&&f(a)?b(a):!0}function h(a){g(a);return f(a)?b(a):!0}function l(a){if(f(a))return b(a);var e=n.mouse.bind[a.button||0];return e?"mousedown"===a.type||"touchstart"===a.type?c(a,e):d(a,e):!0}function m(a){g(a);return l(a)}function p(a){n.accel=a.accelerationIncludingGravity}var n={},r={},q={},t={},s={},u=!1,y=!1,z=
!1,v="mousewheel mousemove mousedown mouseup click dblclick".split(" "),w=[void 0,"touchmove","touchstart","touchend","tap","dbltap"];n.accel={x:0,y:0,z:0};n.mouse={pos:null,offset:null,LEFT:0,MIDDLE:1,RIGHT:2,bind:[0,0,0],handlers:{}};n.touches=[];n.KEY={LEFT:37,UP:38,RIGHT:39,DOWN:40,ENTER:13,SHIFT:16,CTRL:17,ALT:18,PAUSE:19,ESC:27,SPACE:32,NUM0:48,NUM1:49,NUM2:50,NUM3:51,NUM4:52,NUM5:53,NUM6:54,NUM7:55,NUM8:56,NUM9:57,A:65,B:66,C:67,D:68,E:69,F:70,G:71,H:72,I:73,J:74,K:75,L:76,M:77,N:78,O:79,P:80,
Q:81,R:82,S:83,T:84,U:85,V:86,W:87,X:88,Y:89,Z:90};n.isKeyPressed=function(a){return q[a]?(t[a]&&(s[a]=!0,q[a]=!1),!0):!1};n.keyStatus=function(a){return!0===s[a]?!0:q[a]};n.triggerKeyEvent=function(a,b){b?c({},a):d({},a)};n.bindKey=function(a,b,f){u||(e.addEventListener("keydown",c,!1),e.addEventListener("keyup",d,!1),u=!0);r[a]=b;q[b]=!1;t[b]=f?f:!1;s[b]=!1};n.unlockKey=function(a){s[a]=!1};n.unbindKey=function(a){q[r[a]]=!1;t[r[a]]=!1;r[a]=null};n.bindMouse=function(b,d){a();if(!r[d])throw"melonJS : no action defined for keycode "+
d;n.mouse.bind[b]=d};n.unbindMouse=function(a){n.mouse.bind[a]=null};n.bindTouch=function(a){n.bindMouse(me.input.mouse.LEFT,a)};n.unbindTouch=function(){n.unbindMouse(me.input.mouse.LEFT)};n.registerMouseEvent=function(b,d,c,f){a();me.sys.touch&&-1!==v.indexOf(b)&&(b=w[v.indexOf(b)]);if(b&&(-1!==v.indexOf(b)||-1!==w.indexOf(b))){n.mouse.handlers[b]||(n.mouse.handlers[b]=[]);var e=!0===d.floating?!0:!1;f&&(e=!0===f?!0:!1);n.mouse.handlers[b].push({rect:d||null,cb:c,floating:e})}else throw"melonJS : invalid event type : "+
b;};n.releaseMouseEvent=function(a,b){me.sys.touch&&-1!==v.indexOf(a)&&(a=w[v.indexOf(a)]);if(a&&(-1!==v.indexOf(a)||-1!==w.indexOf(a))){n.mouse.handlers[a]||(n.mouse.handlers[a]=[]);var d=n.mouse.handlers[a];if(d)for(var c=d.length,f;c--,f=d[c];)f.rect===b&&(f.rect=f.cb=f.floating=null,n.mouse.handlers[a].splice(c,1))}else throw"melonJS : invalid event type : "+a;};n.watchAccelerometer=function(){return e.sys.gyro?(z||(e.addEventListener("devicemotion",p,!1),z=!0),!0):!1};n.unwatchAccelerometer=
function(){z&&(e.removeEventListener("devicemotion",p,!1),z=!1)};return n}()})(window);
(function(e){var a=function(){return{decode:function(a){a=a.replace(/[^A-Za-z0-9\+\/\=]/g,"");if(me.sys.nativeBase64)return e.atob(a);for(var c=[],d,f,g,k,h,l=0;l<a.length;)d="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(a.charAt(l++)),f="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(a.charAt(l++)),k="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(a.charAt(l++)),h="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(a.charAt(l++)),
d=d<<2|f>>4,f=(f&15)<<4|k>>2,g=(k&3)<<6|h,c.push(String.fromCharCode(d)),64!=k&&c.push(String.fromCharCode(f)),64!=h&&c.push(String.fromCharCode(g));return c=c.join("")}}}();me.utils=function(){var b={},c={},d="",f=0,e=/^.*(\\|\/|\:)/,k=/\.[^\.]*$/;b.decodeBase64=function(b){return a.decode(b)};b.decodeBase64AsArray=function(b,d){d=d||1;var c=a.decode(b),f,e,g,k="function"===typeof window.Uint32Array?new Uint32Array(c.length/d):[];f=0;for(g=c.length/d;f<g;f++){k[f]=0;for(e=d-1;0<=e;--e)k[f]+=c.charCodeAt(f*
d+e)<<(e<<3)}return k};b.decompress=function(a,b){throw"melonJS: GZIP/ZLIB compressed TMX Tile Map not supported!";};b.decodeCSV=function(a,b){a=a.trim().split("\n");for(var d=[],c=0;c<a.length;c++){entries=a[c].split(",",b);for(var f=0;f<entries.length;f++)d.push(+entries[f])}return d};b.getBasename=function(a){return a.replace(e,"").replace(k,"")};b.getFileExtension=function(a){return a.substring(a.lastIndexOf(".")+1,a.length)};b.setNocache=function(a){me.nocache=a?"?"+parseInt(1E7*Math.random()):
""};b.HexToRGB=function(a,b){if("#"!==a.charAt(0))return a;a=a.substring(1,a.length);if(null==c[a]){if(6>a.length)var d=a.charAt(0)+a.charAt(0),f=a.charAt(1)+a.charAt(1),e=a.charAt(2)+a.charAt(2);else d=a.substring(0,2),f=a.substring(2,4),e=a.substring(4,6);c[a]=parseInt(d,16)+","+parseInt(f,16)+","+parseInt(e,16)}return(b?"rgba(":"rgb(")+c[a]+(b?","+b+")":")")};b.RGBToHex=function(a,b,d){return a.toHex()+b.toHex()+d.toHex()};b.getPixels=function(a){if(a instanceof HTMLImageElement){var b=me.video.createCanvasSurface(a.width,
a.height);b.drawImage(a,0,0);return b.getImageData(0,0,a.width,a.height)}return a.getContext("2d").getImageData(0,0,a.width,a.height)};b.resetGUID=function(a){d=a.toString().toUpperCase().toHex();f=0};b.createGUID=function(){return d+"-"+f++};b.applyFriction=function(a,b){return 0>a+b?a+b*me.timer.tick:0<a-b?a-b*me.timer.tick:0};return b}()})(window);
(function(e){function a(a){this.defaultvalue=a||0;this.value=a||0;this.updated=!0}a.prototype.reset=function(){this.set(this.defaultvalue)};a.prototype.update=function(a){return this.set(this.value+a)};a.prototype.set=function(a){this.value=a;return this.updated=!0};me.gamestat=function(){var b={},c={},d=[],f=0;b.add=function(b,e){if(b.constructor===Object)for(var h in b){var l=h;c[l]=new a(b[h]);d.push(c[l]);f++}else c[b]=new a(e),d.push(c[b]),f++};b.updateValue=function(a,b){if(a.constructor===
Object)for(var d in a)c[d]&&c[d].update(a[d]);else c[a]&&c[a].update(b)};b.setValue=function(a,b){if(a.constructor===Object)for(var d in a)c[d]&&c[d].set(a[d]);else c[a]&&c[a].set(b)};b.getItemValue=function(a){return c[a]?c[a].value:0};b.reset=function(a){void 0!=a?c[a]&&c[a].reset():b.resetAll()};b.resetAll=function(){for(var a=f,b;a--,b=d[a];)b.reset()};return b}()})(window);
(function(e){me.COLLISION_LAYER="collision";me.TMX_TAG_MAP="map";me.TMX_TAG_NAME="name";me.TMX_TAG_VALUE="value";me.TMX_TAG_VERSION="version";me.TMX_TAG_ORIENTATION="orientation";me.TMX_TAG_WIDTH="width";me.TMX_TAG_HEIGHT="height";me.TMX_TAG_OPACITY="opacity";me.TMX_TAG_TRANS="trans";me.TMX_TAG_TILEWIDTH="tilewidth";me.TMX_TAG_TILEHEIGHT="tileheight";me.TMX_TAG_TILEOFFSET="tileoffset";me.TMX_TAG_FIRSTGID="firstgid";me.TMX_TAG_GID="gid";me.TMX_TAG_TILE="tile";me.TMX_TAG_ID="id";me.TMX_TAG_DATA="data";
me.TMX_TAG_COMPRESSION="compression";me.TMX_TAG_GZIP="gzip";me.TMX_TAG_ZLIB="zlib";me.TMX_TAG_ENCODING="encoding";me.TMX_TAG_ATTR_BASE64="base64";me.TMX_TAG_CSV="csv";me.TMX_TAG_SPACING="spacing";me.TMX_TAG_MARGIN="margin";me.TMX_TAG_PROPERTIES="properties";me.TMX_TAG_PROPERTY="property";me.TMX_TAG_IMAGE="image";me.TMX_TAG_SOURCE="source";me.TMX_TAG_VISIBLE="visible";me.TMX_TAG_TILESET="tileset";me.TMX_TAG_LAYER="layer";me.TMX_TAG_TILE_LAYER="tilelayer";me.TMX_TAG_IMAGE_LAYER="imagelayer";me.TMX_TAG_OBJECTGROUP=
"objectgroup";me.TMX_TAG_OBJECT="object";me.TMX_TAG_X="x";me.TMX_TAG_Y="y";me.TMX_TAG_WIDTH="width";me.TMX_TAG_HEIGHT="height";me.TMX_TAG_POLYGON="polygon";me.TMX_TAG_POLYLINE="polyline";me.TMX_TAG_POINTS="points";me.TMX_BACKGROUND_COLOR="backgroundcolor"})(window);
(function(e){me.TMXUtils=function(){return{applyTMXPropertiesFromXML:function(a,b){var c=b.getElementsByTagName(me.TMX_TAG_PROPERTIES)[0];if(c)for(var c=c.getElementsByTagName(me.TMX_TAG_PROPERTY),d=0;d<c.length;d++){var f=me.mapReader.TMXParser.getStringAttribute(c[d],me.TMX_TAG_NAME),e=me.mapReader.TMXParser.getStringAttribute(c[d],me.TMX_TAG_VALUE);!e||e.isBoolean()?e=e?"true"==e:!0:e.isNumeric()&&(e=Number(e));a[f]=e}},applyTMXPropertiesFromJSON:function(a,b){var c=b[me.TMX_TAG_PROPERTIES];if(c)for(var d in c)if(c.hasOwnProperty(d)){var f=
c[d];!f||f.isBoolean()?f=f?"true"==f:!0:f.isNumeric()&&(f=Number(f));a[d]=f}},mergeProperties:function(a,b,c){for(var d in b)if(c||void 0===a[d])a[d]=b[d];return a}}}()})(window);
(function(e){me.TMXOBjectGroup=Object.extend({initFromXML:function(a,b,c,d){this.name=a;this.width=me.mapReader.TMXParser.getIntAttribute(b,me.TMX_TAG_WIDTH);this.height=me.mapReader.TMXParser.getIntAttribute(b,me.TMX_TAG_HEIGHT);this.visible=1==me.mapReader.TMXParser.getIntAttribute(b,me.TMX_TAG_VISIBLE,1);this.z=d;this.objects=[];b.firstChild&&b.firstChild.nextSibling.nodeName===me.TMX_TAG_PROPERTIES&&me.TMXUtils.applyTMXPropertiesFromXML(this,b);a=b.getElementsByTagName(me.TMX_TAG_OBJECT);for(b=
0;b<a.length;b++){var f=new me.TMXOBject;f.initFromXML(a[b],c,d);this.objects.push(f)}},initFromJSON:function(a,b,c,d){var f=this;this.name=a;this.width=b[me.TMX_TAG_WIDTH];this.height=b[me.TMX_TAG_HEIGHT];this.visible=b[me.TMX_TAG_VISIBLE];this.z=d;this.objects=[];me.TMXUtils.applyTMXPropertiesFromJSON(this,b);b.objects.forEach(function(a){var b=new me.TMXOBject;b.initFromJSON(a,c,d);f.objects.push(b)})},reset:function(){this.objects=null},getObjectCount:function(){return this.objects.length},getObjectByIndex:function(a){return this.objects[a]}});
me.TMXOBject=Object.extend({initFromXML:function(a,b,c){this.name=me.mapReader.TMXParser.getStringAttribute(a,me.TMX_TAG_NAME);this.x=me.mapReader.TMXParser.getIntAttribute(a,me.TMX_TAG_X);this.y=me.mapReader.TMXParser.getIntAttribute(a,me.TMX_TAG_Y);this.z=c;this.width=me.mapReader.TMXParser.getIntAttribute(a,me.TMX_TAG_WIDTH,0);this.height=me.mapReader.TMXParser.getIntAttribute(a,me.TMX_TAG_HEIGHT,0);if(this.gid=me.mapReader.TMXParser.getIntAttribute(a,me.TMX_TAG_GID,null))this.setImage(this.gid,
b);else if(b=a.getElementsByTagName(me.TMX_TAG_POLYGON),this.isPolygon=!0,b.length||(b=a.getElementsByTagName(me.TMX_TAG_POLYLINE),this.isPolygon=!1),b.length){this.points=[];b=me.mapReader.TMXParser.getStringAttribute(b[0],me.TMX_TAG_POINTS).split(" ");c=0;for(var d;c<b.length;c++)d=b[c].split(","),this.points[c]=new me.Vector2d(+d[0],+d[1])}me.TMXUtils.applyTMXPropertiesFromXML(this,a)},initFromJSON:function(a,b,c){this.name=a[me.TMX_TAG_NAME];this.x=parseInt(a[me.TMX_TAG_X]);this.y=parseInt(a[me.TMX_TAG_Y]);
this.z=parseInt(c);this.width=parseInt(a[me.TMX_TAG_WIDTH]||0);this.height=parseInt(a[me.TMX_TAG_HEIGHT]||0);if(this.gid=parseInt(a[me.TMX_TAG_GID])||null)this.setImage(this.gid,b);else if(b=a[me.TMX_TAG_POLYGON],this.isPolygon=void 0!==b,b||(b=a[me.TMX_TAG_POLYLINE],this.isPolygon=!1),b){this.points=[];var d=this,f=0;b.forEach(function(a){d.points[f++]=new me.Vector2d(parseInt(a.x),parseInt(a.y))})}me.TMXUtils.applyTMXPropertiesFromJSON(this,a)},setImage:function(a,b){var c=b.getTilesetByGid(this.gid);
this.width=c.tilewidth;this.height=c.tileheight;this.spritewidth=this.width;this.y-=c.tileheight;var d=new me.Tile(this.x,this.y,c.tilewidth,c.tileheight,this.gid);this.image=c.getTileImage(d)},getObjectPropertyByName:function(a){return this[a]}})})(window);
(function(e){me.Tile=me.Rect.extend({tileId:null,init:function(a,b,c,d,f){this.parent(new me.Vector2d(a*c,b*d),c,d);this.col=a;this.row=b;this.tileId=f;this.flipX=0!==(this.tileId&2147483648);this.flipY=0!==(this.tileId&1073741824);this.flipAD=0!==(this.tileId&536870912);this.flipped=this.flipX||this.flipY||this.flipAD;this.tileId&=536870911}});me.TMXTileset=Object.extend({type:{SOLID:"solid",PLATFORM:"platform",L_SLOPE:"lslope",R_SLOPE:"rslope",LADDER:"ladder",TOPLADDER:"topladder",BREAKABLE:"breakable"},
init:function(){this.TileProperties=[];this.tileXOffset=[];this.tileYOffset=[]},initFromXML:function(a){this.firstgid=me.mapReader.TMXParser.getIntAttribute(a,me.TMX_TAG_FIRSTGID);var b=me.mapReader.TMXParser.getStringAttribute(a,me.TMX_TAG_SOURCE);if(b){b=me.utils.getBasename(b);a=me.loader.getTMX(b);if(!a)throw"melonJS:"+b+" TSX tileset not found";me.mapReader.TMXParser.parseFromString(a);a=me.mapReader.TMXParser.getFirstElementByTagName("tileset")}this.name=me.mapReader.TMXParser.getStringAttribute(a,
me.TMX_TAG_NAME);this.tilewidth=me.mapReader.TMXParser.getIntAttribute(a,me.TMX_TAG_TILEWIDTH);this.tileheight=me.mapReader.TMXParser.getIntAttribute(a,me.TMX_TAG_TILEHEIGHT);this.spacing=me.mapReader.TMXParser.getIntAttribute(a,me.TMX_TAG_SPACING,0);this.margin=me.mapReader.TMXParser.getIntAttribute(a,me.TMX_TAG_MARGIN,0);this.tileoffset=new me.Vector2d(0,0);b=a.getElementsByTagName(me.TMX_TAG_TILEOFFSET);0<b.length&&(this.tileoffset.x=me.mapReader.TMXParser.getIntAttribute(b[0],me.TMX_TAG_X),this.tileoffset.y=
me.mapReader.TMXParser.getIntAttribute(b[0],me.TMX_TAG_Y));for(var b=a.getElementsByTagName(me.TMX_TAG_TILE),c=0;c<b.length;c++){var d=me.mapReader.TMXParser.getIntAttribute(b[c],me.TMX_TAG_ID)+this.firstgid,f={};me.TMXUtils.applyTMXPropertiesFromXML(f,b[c]);this.setTileProperty(d,f)}(b=(c=a.getElementsByTagName(me.TMX_TAG_IMAGE)[0].getAttribute(me.TMX_TAG_SOURCE))?me.loader.getImage(me.utils.getBasename(c)):null)||console.log("melonJS: '"+c+"' file for tileset '"+this.name+"' not found!");a=a.getElementsByTagName(me.TMX_TAG_IMAGE)[0].getAttribute(me.TMX_TAG_TRANS);
this.initFromImage(b,a)},initFromJSON:function(a){this.firstgid=a[me.TMX_TAG_FIRSTGID];var b=a[me.TMX_TAG_SOURCE];if(b&&(b=me.utils.getBasename(b),a=me.loader.getTMX(b),!a))throw"melonJS:"+b+" TSX tileset not found";this.name=a[me.TMX_TAG_NAME];this.tilewidth=parseInt(a[me.TMX_TAG_TILEWIDTH]);this.tileheight=parseInt(a[me.TMX_TAG_TILEHEIGHT]);this.spacing=parseInt(a[me.TMX_TAG_SPACING]||0);this.margin=parseInt(a[me.TMX_TAG_MARGIN]||0);this.tileoffset=new me.Vector2d(0,0);if(b=a[me.TMX_TAG_TILEOFFSET])this.tileoffset.x=
parseInt(b[me.TMX_TAG_X]),this.tileoffset.y=parseInt(b[me.TMX_TAG_Y]);var b=a.tileproperties,c;for(c in b){var d={};me.TMXUtils.mergeProperties(d,b[c]);this.setTileProperty(parseInt(c)+this.firstgid,d)}(b=(c=me.utils.getBasename(a[me.TMX_TAG_IMAGE]))?me.loader.getImage(c):null)||console.log("melonJS: '"+c+"' file for tileset '"+this.name+"' not found!");this.initFromImage(b,a[me.TMX_TAG_TRANS]||null)},initFromImage:function(a,b){a&&(this.image=a,this.hTileCount=~~((this.image.width-this.margin)/(this.tilewidth+
this.spacing)),this.vTileCount=~~((this.image.height-this.margin)/(this.tileheight+this.spacing)));this.lastgid=this.firstgid+(this.hTileCount*this.vTileCount-1||0);null!==b&&this.image&&(this.image=me.video.applyRGBFilter(this.image,"transparent",b.toUpperCase()).canvas)},setTileProperty:function(a,b){b.isSolid=b.type?b.type.toLowerCase()===this.type.SOLID:!1;b.isPlatform=b.type?b.type.toLowerCase()===this.type.PLATFORM:!1;b.isLeftSlope=b.type?b.type.toLowerCase()===this.type.L_SLOPE:!1;b.isRightSlope=
b.type?b.type.toLowerCase()===this.type.R_SLOPE:!1;b.isBreakable=b.type?b.type.toLowerCase()===this.type.BREAKABLE:!1;b.isLadder=b.type?b.type.toLowerCase()===this.type.LADDER:!1;b.isTopLadder=b.type?b.type.toLowerCase()===this.type.TOPLADDER:!1;b.isSlope=b.isLeftSlope||b.isRightSlope;b.isCollidable=!!b.type;this.TileProperties[a]=b},contains:function(a){return a>=this.firstgid&&a<=this.lastgid},getTileImage:function(a){var b=me.video.createCanvasSurface(this.tilewidth,this.tileheight);this.drawTile(b,
0,0,a);return b.canvas},getTileProperties:function(a){return this.TileProperties[a]},isTileCollidable:function(a){return this.TileProperties[a].isCollidable},getTileOffsetX:function(a){null==this.tileXOffset[a]&&(this.tileXOffset[a]=this.margin+(this.spacing+this.tilewidth)*(a%this.hTileCount));return this.tileXOffset[a]},getTileOffsetY:function(a){null==this.tileYOffset[a]&&(this.tileYOffset[a]=this.margin+(this.spacing+this.tileheight)*~~(a/this.hTileCount));return this.tileYOffset[a]},drawTile:function(a,
b,c,d){if(d.flipped){var f=1,e=0,k=0,h=1,l=b,m=c;b=c=0;a.save();d.flipAD&&(f=0,k=e=1,h=0,m+=this.tileheight-this.tilewidth);d.flipX&&(f=-f,k=-k,l+=d.flipAD?this.tileheight:this.tilewidth);d.flipY&&(e=-e,h=-h,m+=d.flipAD?this.tilewidth:this.tileheight);a.transform(f,e,k,h,l,m)}f=d.tileId-this.firstgid;a.drawImage(this.image,this.getTileOffsetX(f),this.getTileOffsetY(f),this.tilewidth,this.tileheight,b,c,this.tilewidth,this.tileheight);d.flipped&&a.restore()}});me.TMXTilesetGroup=Object.extend({init:function(){this.tilesets=
[]},add:function(a){this.tilesets.push(a)},getTilesetByIndex:function(a){return this.tilesets[a]},getTilesetByGid:function(a){for(var b=-1,c=0,d=this.tilesets.length;c<d;c++){if(this.tilesets[c].contains(a))return this.tilesets[c];this.tilesets[c].firstgid==this.tilesets[c].lastgid&&a>=this.tilesets[c].firstgid&&(b=c)}if(-1!=b)return this.tilesets[b];throw"no matching tileset found for gid "+a;}})})(window);
(function(e){me.TMXOrthogonalRenderer=Object.extend({init:function(a,b,c,d){this.cols=a;this.rows=b;this.tilewidth=c;this.tileheight=d},canRender:function(a){return"orthogonal"===a.orientation&&this.cols===a.cols&&this.rows===a.rows&&this.tilewidth===a.tilewidth&&this.tileheight===a.tileheight},pixelToTileCoords:function(a,b){return new me.Vector2d(a/this.tilewidth,b/this.tileheight)},tileToPixelCoords:function(a,b){return new me.Vector2d(a*this.tilewidth,b*this.tileheight)},drawTile:function(a,b,
c,d,f){f.drawTile(a,f.tileoffset.x+b*this.tilewidth,f.tileoffset.y+(c+1)*this.tileheight-f.tileheight,d)},drawTileLayer:function(a,b,c,d){var f=this.pixelToTileCoords(c.x+d.pos.x,c.y+d.pos.y).floorSelf();c=this.pixelToTileCoords(c.x+d.pos.x+d.width+this.tilewidth,c.y+d.pos.y+d.height+this.tileheight).ceilSelf();c.x=c.x>this.cols?this.cols:c.x;c.y=c.y>this.rows?this.rows:c.y;for(d=f.y;d<c.y;d++)for(var e=f.x;e<c.x;e++){var k=b.layerData[e][d];k&&(b.tileset.contains(k.tileId)||(b.tileset=b.tilesets.getTilesetByGid(k.tileId)),
this.drawTile(a,e,d,k,b.tileset))}}});me.TMXIsometricRenderer=Object.extend({init:function(a,b,c,d){this.cols=a;this.rows=b;this.tilewidth=c;this.tileheight=d;this.hTilewidth=c/2;this.hTileheight=d/2;this.originX=this.rows*this.hTilewidth},canRender:function(a){return"isometric"===a.orientation&&this.cols===a.cols&&this.rows===a.rows&&this.tilewidth===a.tilewidth&&this.tileheight===a.tileheight},pixelToTileCoords:function(a,b){a-=this.originX;var c=b/this.tileheight,d=a/this.tilewidth;return new me.Vector2d(c+
d,c-d)},tileToPixelCoords:function(a,b){return new me.Vector2d((a-b)*this.hTilewidth+this.originX,(a+b)*this.hTileheight)},drawTile:function(a,b,c,d,f){f.drawTile(a,(this.cols-1)*f.tilewidth+(b-c)*f.tilewidth>>1,-f.tilewidth+(b+c)*f.tileheight>>2,d)},drawTileLayer:function(a,b,c,d){var f=b.tileset,e=f.tileoffset,k=this.pixelToTileCoords(c.x+d.pos.x-f.tilewidth,c.y+d.pos.y-f.tileheight).floorSelf(),h=this.pixelToTileCoords(c.x+d.pos.x+d.width+f.tilewidth,c.y+d.pos.y+d.height+f.tileheight).ceilSelf(),
h=this.tileToPixelCoords(h.x,h.y),l=this.tileToPixelCoords(k.x,k.y);l.x-=this.hTilewidth;l.y+=this.tileheight;var m=l.y-d.pos.y+c.y>this.hTileheight;c=d.pos.x+c.x-l.x<this.hTilewidth;m&&(c?(k.x--,l.x-=this.hTilewidth):(k.y--,l.x+=this.hTilewidth),l.y-=this.hTileheight);c^=m;d=k.clone();for(m=l.y;m-this.tileheight<h.y;m+=this.hTileheight){d.setV(k);for(var p=l.x;p<h.x;p+=this.tilewidth){if(0<=d.x&&0<=d.y&&d.x<this.cols&&d.y<this.rows){var n=b.layerData[d.x][d.y];n&&(f.contains(n.tileId)||(f=b.tileset=
b.tilesets.getTilesetByGid(n.tileId),e=f.tileoffset),f.drawTile(a,e.x+p,e.y+m-f.tileheight,n))}d.x++;d.y--}c?(k.y++,l.x-=this.hTilewidth,c=!1):(k.x++,l.x+=this.hTilewidth,c=!0)}}})})(window);
(function(e){me.ColorLayer=me.Renderable.extend({init:function(a,b,c){this.name=a;this.color=me.utils.HexToRGB(b);this.z=c;this.opacity=1;this.floating=!0;this.parent(new me.Vector2d(0,0),me.game.viewport.width,me.game.viewport.height)},reset:function(){},getOpacity:function(){return this.opacity},setOpacity:function(a){"number"===typeof a&&(this.opacity=a.clamp(0,1))},update:function(){return!1},draw:function(a,b){var c=a.globalAlpha;a.globalAlpha=this.opacity;a.fillStyle=this.color;a.fillRect(b.left,
b.top,b.width,b.height);a.globalAlpha=c}});me.ImageLayer=me.Renderable.extend({ratio:1,init:function(a,b,c,d,f,e){this.name=a;this.image=d?me.loader.getImage(me.utils.getBasename(d)):null;if(!this.image)throw"melonJS: '"+d+"' file for Image Layer '"+this.name+"' not found!";this.imagewidth=this.image.width;this.imageheight=this.image.height;this.z=f;this.ratio=e||1;this.viewport=me.game.viewport;this.lastpos=this.viewport.pos.clone();b=b?Math.min(this.viewport.width,b):this.viewport.width;c=c?Math.min(this.viewport.height,
c):this.viewport.height;this.parent(new me.Vector2d(0,0),b,c);this.opacity=1;this.floating=!0;this._repeat="repeat";this.repeatY=this.repeatX=!0;Object.defineProperty(this,"repeat",{get:function(){return this._repeat},set:function(a){this._repeat=a;switch(this._repeat){case "no-repeat":this.repeatY=this.repeatX=!1;break;case "repeat-x":this.repeatX=!0;this.repeatY=!1;break;case "repeat-y":this.repeatX=!1;this.repeatY=!0;break;default:this.repeatY=this.repeatX=!0}}});this.anchorPoint.set(0,0)},reset:function(){this.viewport=
this.lastpos=this.image=null},getOpacity:function(){return this.opacity},setOpacity:function(a){"number"===typeof a&&(this.opacity=a.clamp(0,1))},update:function(){if(0!==this.ratio){var a=this.viewport.pos;if(!this.lastpos.equals(a))return this.pos.x+=(a.x-this.lastpos.x)*this.ratio%this.imagewidth,this.pos.x=(this.imagewidth+this.pos.x)%this.imagewidth,this.pos.y+=(a.y-this.lastpos.y)*this.ratio%this.imageheight,this.pos.y=(this.imageheight+this.pos.y)%this.imageheight,this.lastpos.setV(a),!0}return!1},
draw:function(a,b){a.save();(0!==this.anchorPoint.y||0!==this.anchorPoint.x)&&a.translate(~~(this.anchorPoint.x*(this.viewport.width-this.imagewidth)),~~(this.anchorPoint.y*(this.viewport.height-this.imageheight)));a.globalAlpha=this.opacity;if(0===this.ratio){var c=Math.min(b.width,this.imagewidth),d=Math.min(b.height,this.imageheight);a.drawImage(this.image,b.left,b.top,c,d,b.left,b.top,c,d)}else{var f=~~this.pos.x,e=~~this.pos.y,k=0,h=0,c=Math.min(this.imagewidth-f,this.width),d=Math.min(this.imageheight-
e,this.height);do{do a.drawImage(this.image,f,e,c,d,k,h,c,d),e=0,h+=d,d=Math.min(this.imageheight,this.height-h);while(this.repeatY&&h<this.height);k+=c;if(!this.repeatX||k>=this.width)break;f=0;c=Math.min(this.imagewidth,this.width-k);e=~~this.pos.y;h=0;d=Math.min(this.imageheight-~~this.pos.y,this.height)}while(1)}a.restore()}});me.CollisionTiledLayer=me.Renderable.extend({init:function(a,b){this.parent(new me.Vector2d(0,0),a,b);this.isCollisionMap=!0},reset:function(){},checkCollision:function(a,
b){var c=0>b.x?a.left+b.x:a.right+b.x,d=0>b.y?a.top+b.y:a.bottom+b.y,f={x:0,y:0,xprop:{},yprop:{}};if(0>=c||c>=this.width)f.x=b.x;if(0>=d||d>=this.height)f.y=b.y;return f}});me.TMXLayer=me.Renderable.extend({layerData:null,init:function(a,b,c,d,f){this.tilewidth=a;this.tileheight=b;this.orientation=c;this.z=f;this.tileset=(this.tilesets=d)?this.tilesets.getTilesetByIndex(0):null;this.parent(new me.Vector2d(0,0),0,0)},initFromXML:function(a){this.name=me.mapReader.TMXParser.getStringAttribute(a,me.TMX_TAG_NAME);
this.visible=1==me.mapReader.TMXParser.getIntAttribute(a,me.TMX_TAG_VISIBLE,1);this.opacity=me.mapReader.TMXParser.getFloatAttribute(a,me.TMX_TAG_OPACITY,1).clamp(0,1);this.cols=me.mapReader.TMXParser.getIntAttribute(a,me.TMX_TAG_WIDTH);this.rows=me.mapReader.TMXParser.getIntAttribute(a,me.TMX_TAG_HEIGHT);this.width=this.cols*this.tilewidth;this.height=this.rows*this.tileheight;me.TMXUtils.applyTMXPropertiesFromXML(this,a);void 0===this.preRender&&(this.preRender=me.sys.preRender);if((this.isCollisionMap=
this.name.toLowerCase().contains(me.COLLISION_LAYER))&&!me.debug.renderCollisionMap)this.visible=!1;this.preRender&&(this.layerCanvas=me.video.createCanvas(this.cols*this.tilewidth,this.rows*this.tileheight),this.layerSurface=this.layerCanvas.getContext("2d"),this.layerSurface.globalAlpha=this.opacity)},initFromJSON:function(a){this.name=a[me.TMX_TAG_NAME];this.visible=a[me.TMX_TAG_VISIBLE];this.opacity=parseFloat(a[me.TMX_TAG_OPACITY]).clamp(0,1);this.cols=parseInt(a[me.TMX_TAG_WIDTH]);this.rows=
parseInt(a[me.TMX_TAG_HEIGHT]);this.width=this.cols*this.tilewidth;this.height=this.rows*this.tileheight;me.TMXUtils.applyTMXPropertiesFromJSON(this,a);void 0===this.preRender&&(this.preRender=me.sys.preRender);if((this.isCollisionMap=this.name.toLowerCase().contains(me.COLLISION_LAYER))&&!me.debug.renderCollisionMap)this.visible=!1;this.preRender&&(this.layerCanvas=me.video.createCanvas(this.cols*this.tilewidth,this.rows*this.tileheight),this.layerSurface=this.layerCanvas.getContext("2d"),this.layerSurface.globalAlpha=
this.opacity)},reset:function(){this.preRender&&(this.layerSurface=this.layerCanvas=null);this.tilesets=this.tileset=this.layerData=this.renderer=null},setRenderer:function(a){this.renderer=a},initArray:function(a,b){this.layerData=[];for(var c=0;c<a;c++){this.layerData[c]=[];for(var d=0;d<b;d++)this.layerData[c][d]=null}},getTileId:function(a,b){var c=this.getTile(a,b);return c?c.tileId:null},getTile:function(a,b){return this.layerData[~~(a/this.tilewidth)][~~(b/this.tileheight)]},setTile:function(a,
b,c){this.layerData[a][b]=new me.Tile(a,b,this.tilewidth,this.tileheight,c)},clearTile:function(a,b){this.layerData[a][b]=null;this.visible&&this.preRender&&this.layerSurface.clearRect(a*this.tilewidth,b*this.tileheight,this.tilewidth,this.tileheight)},getOpacity:function(){return this.opacity},setOpacity:function(a){"number"===typeof a&&(this.opacity=a.clamp(0,1),this.preRender&&(this.layerSurface.globalAlpha=this.opacity))},checkCollision:function(a,b){var c=0>b.x?~~(a.left+b.x):Math.ceil(a.right-
1+b.x),d=0>b.y?~~(a.top+b.y):Math.ceil(a.bottom-1+b.y),f={x:0,xtile:void 0,xprop:{},y:0,ytile:void 0,yprop:{}};0>=c||c>=this.width?f.x=b.x:0!=b.x&&(f.xtile=this.getTile(c,Math.ceil(a.bottom-1)),f.xtile&&this.tileset.isTileCollidable(f.xtile.tileId)?(f.x=b.x,f.xprop=this.tileset.getTileProperties(f.xtile.tileId)):(f.xtile=this.getTile(c,~~a.top),f.xtile&&this.tileset.isTileCollidable(f.xtile.tileId)&&(f.x=b.x,f.xprop=this.tileset.getTileProperties(f.xtile.tileId))));f.ytile=this.getTile(0>b.x?~~a.left:
Math.ceil(a.right-1),d);f.ytile&&this.tileset.isTileCollidable(f.ytile.tileId)?(f.y=b.y||1,f.yprop=this.tileset.getTileProperties(f.ytile.tileId)):(f.ytile=this.getTile(0>b.x?Math.ceil(a.right-1):~~a.left,d),f.ytile&&this.tileset.isTileCollidable(f.ytile.tileId)&&(f.y=b.y||1,f.yprop=this.tileset.getTileProperties(f.ytile.tileId)));return f},update:function(){return!1},draw:function(a,b){var c=me.game.viewport.pos;if(this.preRender){var d=Math.min(b.width,this.width),f=Math.min(b.height,this.height);
a.drawImage(this.layerCanvas,c.x+b.pos.x,c.y+b.pos.y,d,f,c.x+b.pos.x,c.y+b.pos.y,d,f)}else d=a.globalAlpha,a.globalAlpha=this.opacity,this.renderer.drawTileLayer(a,this,c,b),a.globalAlpha=d}})})(window);
(function(e){me.TMXTileMap=me.Renderable.extend({init:function(a,b,c){this.levelId=a;this.z=0;this.name=null;this.tileheight=this.tilewidth=this.rows=this.cols=0;this.tilesets=null;this.mapLayers=[];this.objectGroups=[];this.initialized=!1;this.orientation=this.version="";this.tilesets=null;this.parent(new me.Vector2d(b,c),0,0)},reset:function(){if(!0===this.initialized){for(var a=this.mapLayers.length;a--;)this.mapLayers[a].reset(),this.mapLayers[a]=null;for(a=this.objectGroups.length;a--;)this.objectGroups[a].reset(),
this.objectGroups[a]=null;this.tilesets=null;this.mapLayers.length=0;this.objectGroups.length=0;this.pos.set(0,0);this.initialized=!1}},getObjectGroupByName:function(a){var b=null;a=a.trim().toLowerCase();for(var c=this.objectGroups.length;c--;)if(this.objectGroups[c].name.toLowerCase().contains(a)){b=this.objectGroups[c];break}return b},getObjectGroups:function(){return this.objectGroups},getLayers:function(){return this.mapLayers},getLayerByName:function(a){var b=null;a=a.trim().toLowerCase();for(var c=
this.mapLayers.length;c--;)if(this.mapLayers[c].name.toLowerCase().contains(a)){b=this.mapLayers[c];break}a.toLowerCase().contains(me.COLLISION_LAYER)&&null==b&&(b=new me.CollisionTiledLayer(me.game.currentLevel.width,me.game.currentLevel.height));return b},clearTile:function(a,b){for(var c=this.mapLayers.length;c--;)this.mapLayers[c]instanceof me.TMXLayer&&this.mapLayers[c].clearTile(a,b)}})})(window);
(function(e){function a(){return{tmxDoc:null,setData:function(a){this.tmxDoc=a},getFirstElementByTagName:function(a){return this.tmxDoc?this.tmxDoc.getElementsByTagName(a)[0]:null},getAllTagElements:function(){return this.tmxDoc?this.tmxDoc.getElementsByTagName("*"):null},getStringAttribute:function(a,b,c){return(a=a.getAttribute(b))?a.trim():c},getIntAttribute:function(a,b,c){return(a=this.getStringAttribute(a,b,c))?parseInt(a):c},getFloatAttribute:function(a,b,c){return(a=this.getStringAttribute(a,
b,c))?parseFloat(a):c},getBooleanAttribute:function(a,b,c){return(a=this.getStringAttribute(a,b,c))?"true"==a:c},free:function(){this.tmxDoc=null}}}me.TMXMapReader=Object.extend({XMLReader:null,JSONReader:null,TMXParser:null,readMap:function(a){if(!a.initialized){"xml"===me.loader.getTMXFormat(a.levelId)?(null===this.XMLReader&&(this.XMLReader=new b),this.TMXParser=this.XMLReader.TMXParser,this.XMLReader.readXMLMap(a,me.loader.getTMX(a.levelId))):(null===this.JSONReader&&(this.JSONReader=new c),this.JSONReader.readJSONMap(a,
me.loader.getTMX(a.levelId)));if(a.width<me.game.viewport.width||a.height<me.game.viewport.height){var f=~~((me.game.viewport.width-a.width)/2),e=~~((me.game.viewport.height-a.height)/2);a.pos.add({x:0<f?f:0,y:0<e?e:0})}a.initialized=!0}},getNewDefaultRenderer:function(a){switch(a.orientation){case "orthogonal":return new me.TMXOrthogonalRenderer(a.cols,a.rows,a.tilewidth,a.tileheight);case "isometric":return new me.TMXIsometricRenderer(a.cols,a.rows,a.tilewidth,a.tileheight);default:throw"melonJS: "+
a.orientation+" type TMX Tile Map not supported!";}},setLayerData:function(a,b,c,e){a.initArray(a.cols,a.rows);switch(c){case null:b=b.getElementsByTagName(me.TMX_TAG_TILE);break;case "json":break;case me.TMX_TAG_CSV:case me.TMX_TAG_ATTR_BASE64:for(var h="",l=0,m=b.childNodes.length;l<m;l++)h+=b.childNodes[l].nodeValue;c==me.TMX_TAG_CSV?b=me.utils.decodeCSV(h,a.cols):(b=me.utils.decodeBase64AsArray(h,4),null!==e&&(b=me.utils.decompress(b,e)));break;default:throw"melonJS: TMX Tile Map "+c+" encoding not supported!";
}for(h=e=0;h<a.rows;h++)for(l=0;l<a.cols;l++)m=null==c?this.TMXParser.getIntAttribute(b[e++],me.TMX_TAG_GID):b[e++],0!==m&&(m=new me.Tile(l,h,a.tilewidth,a.tileheight,m),a.layerData[l][h]=m,a.tileset.contains(m.tileId)||(a.tileset=a.tilesets.getTilesetByGid(m.tileId)),a.visible&&a.preRender&&a.renderer.drawTile(a.layerSurface,l,h,m,a.tileset))}});var b=me.TMXMapReader.extend({TMXParser:null,init:function(){this.TMXParser||(this.TMXParser=new a)},readXMLMap:function(a,b){if(!b)throw"melonJS:"+a.levelId+
" TMX map not found";var c=0;this.TMXParser.setData(b);for(var e=this.TMXParser.getAllTagElements(),h=0;h<e.length;h++)switch(e.item(h).nodeName){case me.TMX_TAG_MAP:var l=e.item(h);a.version=this.TMXParser.getStringAttribute(l,me.TMX_TAG_VERSION);a.orientation=this.TMXParser.getStringAttribute(l,me.TMX_TAG_ORIENTATION);a.cols=this.TMXParser.getIntAttribute(l,me.TMX_TAG_WIDTH);a.rows=this.TMXParser.getIntAttribute(l,me.TMX_TAG_HEIGHT);a.tilewidth=this.TMXParser.getIntAttribute(l,me.TMX_TAG_TILEWIDTH);
a.tileheight=this.TMXParser.getIntAttribute(l,me.TMX_TAG_TILEHEIGHT);a.width=a.cols*a.tilewidth;a.height=a.rows*a.tileheight;a.backgroundcolor=this.TMXParser.getStringAttribute(l,me.TMX_BACKGROUND_COLOR);a.z=c++;me.TMXUtils.applyTMXPropertiesFromXML(a,l);a.background_color=a.backgroundcolor?a.backgroundcolor:a.background_color;a.background_color&&a.mapLayers.push(new me.ColorLayer("background_color",a.background_color,c++));a.background_image&&a.mapLayers.push(new me.ImageLayer("background_image",
a.width,a.height,a.background_image,c++));if(null===me.game.renderer||!me.game.renderer.canRender(a))me.game.renderer=this.getNewDefaultRenderer(a);break;case me.TMX_TAG_TILESET:a.tilesets||(a.tilesets=new me.TMXTilesetGroup);a.tilesets.add(this.readTileset(e.item(h)));break;case me.TMX_TAG_IMAGE_LAYER:a.mapLayers.push(this.readImageLayer(a,e.item(h),c++));break;case me.TMX_TAG_LAYER:a.mapLayers.push(this.readLayer(a,e.item(h),c++));break;case me.TMX_TAG_OBJECTGROUP:a.objectGroups.push(this.readObjectGroup(a,
e.item(h),c++))}this.TMXParser.free()},readLayer:function(a,b,c){a=new me.TMXLayer(a.tilewidth,a.tileheight,a.orientation,a.tilesets,c);a.initFromXML(b);b=b.getElementsByTagName(me.TMX_TAG_DATA)[0];c=this.TMXParser.getStringAttribute(b,me.TMX_TAG_ENCODING,null);var e=this.TMXParser.getStringAttribute(b,me.TMX_TAG_COMPRESSION,null);""==c&&(c=null);""==e&&(e=null);if(!a.isCollisionMap||me.debug.renderCollisionMap)me.game.renderer.canRender(a)?a.setRenderer(me.game.renderer):a.setRenderer(me.mapReader.getNewDefaultRenderer(a));
this.setLayerData(a,b,c,e);return a},readImageLayer:function(a,b,c){var e=this.TMXParser.getStringAttribute(b,me.TMX_TAG_NAME),h=this.TMXParser.getIntAttribute(b,me.TMX_TAG_WIDTH),l=this.TMXParser.getIntAttribute(b,me.TMX_TAG_HEIGHT),m=b.getElementsByTagName(me.TMX_TAG_IMAGE)[0].getAttribute(me.TMX_TAG_SOURCE);a=new me.ImageLayer(e,h*a.tilewidth,l*a.tileheight,m,c);a.visible=1==this.TMXParser.getIntAttribute(b,me.TMX_TAG_VISIBLE,1);a.opacity=this.TMXParser.getFloatAttribute(b,me.TMX_TAG_OPACITY,1);
me.TMXUtils.applyTMXPropertiesFromXML(a,b);return a},readTileset:function(a){var b=new me.TMXTileset;b.initFromXML(a);return b},readObjectGroup:function(a,b,c){var e=this.TMXParser.getStringAttribute(b,me.TMX_TAG_NAME),h=new me.TMXOBjectGroup;h.initFromXML(e,b,a.tilesets,c);return h}}),c=me.TMXMapReader.extend({readJSONMap:function(a,b){if(!b)throw"melonJS:"+a.levelId+" TMX map not found";var c=0,e=this;a.version=b[me.TMX_TAG_VERSION];a.orientation=b[me.TMX_TAG_ORIENTATION];a.cols=parseInt(b[me.TMX_TAG_WIDTH]);
a.rows=parseInt(b[me.TMX_TAG_HEIGHT]);a.tilewidth=parseInt(b[me.TMX_TAG_TILEWIDTH]);a.tileheight=parseInt(b[me.TMX_TAG_TILEHEIGHT]);a.width=a.cols*a.tilewidth;a.height=a.rows*a.tileheight;a.backgroundcolor=b[me.TMX_BACKGROUND_COLOR];a.z=c++;me.TMXUtils.applyTMXPropertiesFromJSON(a,b);a.background_color=a.backgroundcolor?a.backgroundcolor:a.background_color;a.background_color&&a.mapLayers.push(new me.ColorLayer("background_color",a.background_color,c++));a.background_image&&a.mapLayers.push(new me.ImageLayer("background_image",
a.width,a.height,a.background_image,c++));if(null===me.game.renderer||!me.game.renderer.canRender(a))me.game.renderer=this.getNewDefaultRenderer(a);a.tilesets||(a.tilesets=new me.TMXTilesetGroup);b.tilesets.forEach(function(b){a.tilesets.add(e.readTileset(b))});b.layers.forEach(function(b){switch(b.type){case me.TMX_TAG_IMAGE_LAYER:a.mapLayers.push(e.readImageLayer(a,b,c++));break;case me.TMX_TAG_TILE_LAYER:a.mapLayers.push(e.readLayer(a,b,c++));break;case me.TMX_TAG_OBJECTGROUP:a.objectGroups.push(e.readObjectGroup(a,
b,c++))}})},readLayer:function(a,b,c){a=new me.TMXLayer(a.tilewidth,a.tileheight,a.orientation,a.tilesets,c);a.initFromJSON(b);a.isCollisionMap||(me.game.renderer.canRender(a)?a.setRenderer(me.game.renderer):a.setRenderer(me.mapReader.getNewDefaultRenderer(a)));this.setLayerData(a,b[me.TMX_TAG_DATA],"json",null);return a},readImageLayer:function(a,b,c){var e=b[me.TMX_TAG_NAME],h=parseInt(b[me.TMX_TAG_WIDTH]),l=parseInt(b[me.TMX_TAG_HEIGHT]);a=new me.ImageLayer(e,h*a.tilewidth,l*a.tileheight,b[me.TMX_TAG_IMAGE],
c);a.visible=b[me.TMX_TAG_VISIBLE];a.opacity=parseFloat(b[me.TMX_TAG_OPACITY]);me.TMXUtils.applyTMXPropertiesFromJSON(a,b);a.ratio=parseFloat(a.ratio);return a},readTileset:function(a){var b=new me.TMXTileset;b.initFromJSON(a);return b},readObjectGroup:function(a,b,c){var e=new me.TMXOBjectGroup;e.initFromJSON(b[me.TMX_TAG_NAME],b,a.tilesets,c);return e}})})(window);
(function(e){me.levelDirector=function(){var a={},b={},c=[],d=0;a.reset=function(){};a.addLevel=function(a){throw"melonJS: no level loader defined";};a.addTMXLevel=function(a,d){if(null==b[a])b[a]=new me.TMXTileMap(a,0,0),b[a].name=a,c[c.length]=a;else return!1;d&&d();return!0};a.loadLevel=function(e){e=e.toString().toLowerCase();if(void 0===b[e])throw"melonJS: level "+e+" not found";if(b[e]instanceof me.TMXTileMap){var g=me.state.isRunning();g&&me.state.pause();me.game.reset();me.utils.resetGUID(e);
b[a.getCurrentLevelId()]&&b[a.getCurrentLevelId()].reset();me.mapReader.readMap(b[e]);d=c.indexOf(e);me.game.loadTMXLevel(b[e]);g&&me.state.resume()}else throw"melonJS: no level loader defined";return!0};a.getCurrentLevelId=function(){return c[d]};a.reloadLevel=function(){return a.loadLevel(a.getCurrentLevelId())};a.nextLevel=function(){return d+1<c.length?a.loadLevel(c[d+1]):!1};a.previousLevel=function(){return 0<=d-1?a.loadLevel(c[d-1]):!1};a.levelCount=function(){return c.length};return a}()})(window);
(function(){me.Tween=function(e){var a={},b={},c={},d=1E3,f=0,g=null,k=0,h=me.Tween.Easing.Linear.EaseNone,l=null,m=null,p=null;this.to=function(a,b){void 0!==b&&(d=b);for(var f in a)null!==e[f]&&(c[f]=a[f]);return this};this.start=function(){me.game.add(this,999);g=me.timer.getTime()+f;k=0;for(var d in c)null!==e[d]&&(a[d]=e[d],b[d]=c[d]-e[d]);return this};this.stop=function(){me.game.remove(this);return this};this.delay=function(a){f=a;return this};me.event.subscribe(me.event.STATE_PAUSE,function(){g&&
(k=me.timer.getTime())});me.event.subscribe(me.event.STATE_RESUME,function(){g&&k&&(g+=me.timer.getTime()-k)});this.easing=function(a){h=a;return this};this.chain=function(a){l=a;return this};this.onUpdate=function(a){m=a;return this};this.onComplete=function(a){p=a;return this};this.update=function(){var c,f,k;f=me.timer.getTime();if(f<g)return!0;if(1<=(f=(f-g)/d))f=1;k=h(f);for(c in b)e[c]=a[c]+b[c]*k;null!==m&&m.call(e,k);return 1===f?(me.game.remove(this),null!==p&&p.call(e),null!==l&&l.start(),
!1):!0}};me.Tween.Easing={Linear:{},Quadratic:{},Cubic:{},Quartic:{},Quintic:{},Sinusoidal:{},Exponential:{},Circular:{},Elastic:{},Back:{},Bounce:{}};me.Tween.Easing.Linear.EaseNone=function(e){return e};me.Tween.Easing.Quadratic.EaseIn=function(e){return e*e};me.Tween.Easing.Quadratic.EaseOut=function(e){return e*(2-e)};me.Tween.Easing.Quadratic.EaseInOut=function(e){return 1>(e*=2)?0.5*e*e:-0.5*(--e*(e-2)-1)};me.Tween.Easing.Cubic.EaseIn=function(e){return e*e*e};me.Tween.Easing.Cubic.EaseOut=
function(e){return--e*e*e+1};me.Tween.Easing.Cubic.EaseInOut=function(e){return 1>(e*=2)?0.5*e*e*e:0.5*((e-=2)*e*e+2)};me.Tween.Easing.Quartic.EaseIn=function(e){return e*e*e*e};me.Tween.Easing.Quartic.EaseOut=function(e){return 1- --e*e*e*e};me.Tween.Easing.Quartic.EaseInOut=function(e){return 1>(e*=2)?0.5*e*e*e*e:-0.5*((e-=2)*e*e*e-2)};me.Tween.Easing.Quintic.EaseIn=function(e){return e*e*e*e*e};me.Tween.Easing.Quintic.EaseOut=function(e){return--e*e*e*e*e+1};me.Tween.Easing.Quintic.EaseInOut=function(e){return 1>
(e*=2)?0.5*e*e*e*e*e:0.5*((e-=2)*e*e*e*e+2)};me.Tween.Easing.Sinusoidal.EaseIn=function(e){return 1-Math.cos(e*Math.PI/2)};me.Tween.Easing.Sinusoidal.EaseOut=function(e){return Math.sin(e*Math.PI/2)};me.Tween.Easing.Sinusoidal.EaseInOut=function(e){return 0.5*(1-Math.cos(Math.PI*e))};me.Tween.Easing.Exponential.EaseIn=function(e){return 0===e?0:Math.pow(1024,e-1)};me.Tween.Easing.Exponential.EaseOut=function(e){return 1===e?1:1-Math.pow(2,-10*e)};me.Tween.Easing.Exponential.EaseInOut=function(e){return 0===
e?0:1===e?1:1>(e*=2)?0.5*Math.pow(1024,e-1):0.5*(-Math.pow(2,-10*(e-1))+2)};me.Tween.Easing.Circular.EaseIn=function(e){return 1-Math.sqrt(1-e*e)};me.Tween.Easing.Circular.EaseOut=function(e){return Math.sqrt(1- --e*e)};me.Tween.Easing.Circular.EaseInOut=function(e){return 1>(e*=2)?-0.5*(Math.sqrt(1-e*e)-1):0.5*(Math.sqrt(1-(e-=2)*e)+1)};me.Tween.Easing.Elastic.EaseIn=function(e){var a,b=0.1;if(0===e)return 0;if(1===e)return 1;!b||1>b?(b=1,a=0.1):a=0.4*Math.asin(1/b)/(2*Math.PI);return-(b*Math.pow(2,
10*(e-=1))*Math.sin((e-a)*2*Math.PI/0.4))};me.Tween.Easing.Elastic.EaseOut=function(e){var a,b=0.1;if(0===e)return 0;if(1===e)return 1;!b||1>b?(b=1,a=0.1):a=0.4*Math.asin(1/b)/(2*Math.PI);return b*Math.pow(2,-10*e)*Math.sin((e-a)*2*Math.PI/0.4)+1};me.Tween.Easing.Elastic.EaseInOut=function(e){var a,b=0.1;if(0===e)return 0;if(1===e)return 1;!b||1>b?(b=1,a=0.1):a=0.4*Math.asin(1/b)/(2*Math.PI);return 1>(e*=2)?-0.5*b*Math.pow(2,10*(e-=1))*Math.sin((e-a)*2*Math.PI/0.4):0.5*b*Math.pow(2,-10*(e-=1))*Math.sin((e-
a)*2*Math.PI/0.4)+1};me.Tween.Easing.Back.EaseIn=function(e){return e*e*(2.70158*e-1.70158)};me.Tween.Easing.Back.EaseOut=function(e){return--e*e*(2.70158*e+1.70158)+1};me.Tween.Easing.Back.EaseInOut=function(e){return 1>(e*=2)?0.5*e*e*(3.5949095*e-2.5949095):0.5*((e-=2)*e*(3.5949095*e+2.5949095)+2)};me.Tween.Easing.Bounce.EaseIn=function(e){return 1-me.Tween.Easing.Bounce.EaseOut(1-e)};me.Tween.Easing.Bounce.EaseOut=function(e){return e<1/2.75?7.5625*e*e:e<2/2.75?7.5625*(e-=1.5/2.75)*e+0.75:e<2.5/
2.75?7.5625*(e-=2.25/2.75)*e+0.9375:7.5625*(e-=2.625/2.75)*e+0.984375};me.Tween.Easing.Bounce.EaseInOut=function(e){return 0.5>e?0.5*me.Tween.Easing.Bounce.EaseIn(2*e):0.5*me.Tween.Easing.Bounce.EaseOut(2*e-1)+0.5}})();
(function(){me.event=function(){var e={},a={};e.STATE_PAUSE="me.state.onPause";e.STATE_RESUME="me.state.onResume";e.GAME_INIT="me.game.onInit";e.LEVEL_LOADED="me.game.onLevelLoaded";e.LOADER_COMPLETE="me.loader.onload";e.LOADER_PROGRESS="me.loader.onProgress";e.KEYDOWN="me.input.keydown";e.KEYUP="me.input.keyup";e.WINDOW_ONRESIZE="window.onresize";e.publish=function(b,c){for(var d=a[b],e=d?d.length:0;e--;)d[e].apply(window,c||[])};e.subscribe=function(b,c){a[b]||(a[b]=[]);a[b].push(c);return[b,c]};
e.unsubscribe=function(b,c){var d=a[c?b:b[0]];c=c||b[1];for(var e=d?d.length:0;e--;)d[e]===c&&d.splice(e,1)};return e}()})();
(function(){me.plugin=function(){var e={};e.Base=Object.extend({version:void 0,init:function(){}});e.patch=function(a,b,c){void 0!==a.prototype&&(a=a.prototype);if("function"==typeof a[b]){var d=a[b];a[b]=function(a,b){return function(){var a=this.parent;this.parent=d;var c=b.apply(this,arguments);this.parent=a;return c}}(b,c)}else console.error(b+" is not an existing function")};e.register=function(a,b){me.plugin[b]&&console.error("plugin "+b+" already registered");if(void 0===a.prototype.version)throw"melonJS: Plugin version not defined !";
if(0<me.sys.checkVersion(a.prototype.version))throw"melonJS: Plugin version mismatch, expected: "+a.prototype.version+", got: "+me.version;var c=[];2<arguments.length&&(c=Array.prototype.slice.call(arguments,1));c[0]=a;me.plugin[b]=new (a.bind.apply(a,c));if(!(me.plugin[b]instanceof me.plugin.Base))throw"melonJS: Plugin should extend the me.plugin.Base Class !";};return e}()})();
